### ISSUE TITLE
Internal error in neon module when using stacks-devnet-js

### ISSUE THREAD

**Issue by friedger** [hirosystems/clarinet#1025]
My project contains unit tests (`clarinet test`) , integration tests (`vitest`) and deployment plans (`clarinet integrate`).

Using the current branch feat/devnet-epoch-2.2, I get the following errors when running vitest:

`internal error in Neon module: Syntax error in Clarinet.toml.: "epoch field invalid (value supported: 2.0, 2.05, 2.1)"`

after removing epoch field:

`internal error in Neon module: Syntax error in Clarinet.toml.: "Clarity 2 can not be used with 2.05"`

**Comment by friedger** [comment]
building stacks-devnet-js again solves the issue

**Comment by obycode** [comment]
We spoke about this and it seems the problem is just that `stacks-devnet-js` needed to be rebuilt. Once these updates are released, this should not be a problem. Ok to close @friedger?

**Comment by obycode** [comment]
I guess so 🤣
