### ISSUE TITLE
Safety check on --coverage custom file name

### ISSUE THREAD

**Issue by hugocaillard** [hirosystems/clarinet#1029]
I run the following command to only run the tests of the `contract1.ts` file:
```sh
clarinet test --coverage ./tests/contract1.ts
# used to work in v1.5
```

Instead of
```
clarinet test  ./tests/contract1.ts --coverage
```

As a result, it replaced my tests with with the coverage.

It's caused by the fact the we can now specify the name of the output coverage file.

### Current behavior

Replaces the ts test file with the coverage report.

### Expected behavior

Maybe we should throw and error "invalid file name for coverage output, it should end with *.ts". Or allow only .lcov

**Comment by MicaiahReid** [comment]
@hugocaillard and I discussed this and think it's safe to close.

Before the clarinet sdk, the `--coverage` field was both an enable/boolean flag _and_ could allow an input to specify the test output filename.

With the clarinet sdk, these are separate fields, `--coverage` and `--coverageFilename`. While it's still possible to specify `--coverageFilename` and overwrite your test files, this new field is very clear that the following value will be the coverage file output, so it's unlikely that people will accidentally overwrite their files.
