### ISSUE TITLE
Comments that do not survive deploy; or, pre-processor scripts

### ISSUE THREAD

**Issue by MarvinJanssen** [hirosystems/clarinet#1041]
Some of us have been sparse in adding comments in the sBTC contracts because of a "worry" that heavily commenting the code will in the end lead to increased read_count costs. (I know, premature optimisation.) Still, it got us talking about types of comments that would not survive a deploy. If something like that existed then we could be a lot more generous with comments and take a more "literate programming" approach to describing the intent of routines that are useful during development but not once deployed.

We thought about some ways, for example comments that are prefixed by thee semi-colons `;;;` could be filtered out. Although that could probably affect existing code bases, so perhaps a different suggestion would be needed.

```clarity
;; This comment will be part of deployment
;;; This comment won't be.
```

Thoughts? Does it make sense to have a feature such as this in Clarinet? Or would it be possible to run a pre-deployment TS script in which we can filter such comments?

**Comment by hugocaillard** [comment]
I think we could make it part of this SIP https://github.com/stacksgov/sips/pull/32
Which is definitely something we want to work on in the clarinet team.

And the SIP could be something like "Special comments in Clarity" (idk if there's a technical term for that). Including:
- contract documentation comments
- filtered out comment

We have to be careful with the syntax. I was thinking it would make sense to have the `;;;` for the "documentation comments (just like JSDoc uses `/**`).

@MarvinJanssen Does it make sense to you to include it in the SIP? Could you add a comment over there and we'll close this PR?

Thanks!

(Note: and even if the SIP is not approved or definitive in the next quarters, `clarinet` could still benefit from this proposals)

Could you add a comment here

**Comment by hugocaillard** [comment]
Hey Marvin, have you seen my previous comment?
I'll close this one, feel free to add a comment on [stacksgov/sips#32](https://github.com/stacksgov/sips/pull/32) or re-open this on if you think it's more relevant
