### ISSUE TITLE
Crash in `clarinet check` and LSP

### ISSUE THREAD

**Issue by obycode** [hirosystems/clarinet#1043]
I accidentally discovered that this unusual but valid Clarity code causes a crash on the command line or in the LSP:

```clarity
(at-block 0x9f5c0df2f04da020ad0283bbbb365ae177fc32593037f29727eb97a03ba4340e (get-block-info? id-header-hash u108171))
```

```
panicked at 'No height stored for current chain tip', components/clarity-repl/src/repl/datastore.rs:223:9
```

**Comment by hugocaillard** [comment]
What is the expected behavior?

Do we only want to prevent the crash (and return some default value?)

**Comment by obycode** [comment]
Yes, I'd say definitely prevent the crash and then recover by providing as much functionality as possible with a failing build.
