### ISSUE TITLE
Clarinet stop working when adding requirement SP3K8BC0PPEVCV7NZ6QSRWPQ2JE9E5B6N3PA0KBR9.amm-swap-pool-v1-1

### ISSUE THREAD

**Issue by pradel** [hirosystems/clarinet#1079]
When I add `SP3K8BC0PPEVCV7NZ6QSRWPQ2JE9E5B6N3PA0KBR9.amm-swap-pool-v1-1` as a requirement of my project, clarinet stop working, clarinet check is never responding and vscode stop reporting clarity issues for my contract.

## To reproduce

1. Create a new project `clarinet new test`
2. Create an empty contract `clarinet contract new mycontract`
3. Add the requirement `clarinet requirements add SP3K8BC0PPEVCV7NZ6QSRWPQ2JE9E5B6N3PA0KBR9.amm-swap-pool-v1-1`
4. See clarinet freeze `clarinet check`

**Comment by hugocaillard** [comment]
The for reporting the issue @pradel, the fix will be released this week

**Comment by hugocaillard** [comment]
Thanks @pradel 
clarinet v1.71. and clarity for vscode v1.7.2 have been released with a fiw

**Comment by pradel** [comment]
@hugocaillard thanks!
