### ISSUE TITLE
Nakamoto compatibility for clarinet

### ISSUE THREAD

**Issue by smcclellan** [hirosystems/clarinet#1083]
In scope:
- Clarity WASM integration
- Support running 3.0 in clarinet integrate (once a docker image is available for the node)
- Use the new Clarity VM in simnet (console and tests) as soon as the API is stable (maybe now)
- Exposing sBTC signer protocol for configuration in devnet
- Exposing pegs-in-and-out configurations for devnet

/cc @hugocaillard

**Comment by hugocaillard** [comment]
Closing this issue since it's split into multiple ones
