### ISSUE TITLE
Add the `clarinet devnet package` command

### ISSUE THREAD

**Issue by MicaiahReid** [hirosystems/clarinet#1102]
#1059 Outlines what this could look like specifically for clarinet deployments. This issue is to implement that same feature, but for all relevant devnet files.

**Comment by andresgalante** [comment]
@csgui what's the lastest for this issue?

**Comment by andresgalante** [comment]
We'll need this in ~2 weeks

**Comment by smcclellan** [comment]
@andresgalante

**Comment by MicaiahReid** [comment]
Closed by #1116
