### ISSUE TITLE
Non-zero error codes from Deno are not propagated for clarinet run scripts

### ISSUE THREAD

**Issue by MarvinJanssen** [hirosystems/clarinet#1107]
**Describe the bug**
Non-zero error codes from Deno are not propagated for clarinet run scripts. I created a `clarinet run` script that exits with a non-zero error code using `Deno.exit(1);` for the purpose of checking aspects code base. I would like to run this script in CI and have it fail if the checks fail.

**To Reproduce**
1. Create a `clarinet run` script and add `Deno.exit(1);`
2. Run the script, you see something like:
```
error: AssertionError: Test case attempted to exit with exit code: 1
         Deno.exit(1);
```
3. Print the exit code to see it is zero:
```
% echo $?
0
```

**Expected behavior**
The exit code should be propagated by Clarinet.

**Additional context**
I noticed bug when I added the script to a GH Action. You can see the run here: https://github.com/Trust-Machines/stacks-sbtc/actions/runs/5700176285/job/15449771013?pr=605

**Comment by smcclellan** [comment]
@MarvinJanssen Is this a blocker for you?

**Comment by hugocaillard** [comment]
Hey @MarvinJanssen 
I'm closing this issue because `clarinet run` will be removed in the upcoming releases on clarinet.
Let me know if you want more details
