### ISSUE TITLE
Build JS Clarinet test lib on top the core SDK

### ISSUE THREAD

**Issue by hugocaillard** [hirosystems/clarinet#1109]
The clarinet core JS SDK allows to load a clarinet session and interact with it (call functions, get contracts interfaces - ABI, get devnet.toml accounts and get the assets per addresses/contracts).

While the core SDK will allow to interact with a session in many ways, the test kit should provide a nice and easy way to test clarity contracts. It will be the recommended way to test clarinet projects.

- The test kit library expose a more developer friendly testing API thanks to helpers and wrappers around  `core`
- Should handle code coverage out of the box in a an easy way
- Some assertion features for clarity values and events.
- We should also provide a **clarinet 1 compatibility layer** (`test-compat`) on top of `core` and `test-kit` that will implement the exact same API as the Deno testing library (`Clarinet.test`, `String.prototype.expect*`) to ease the transition of existing projects from the clarinet 1 / deno testing framework to the new one.

**Comment by sabbyanandan** [comment]
@hugocaillard: Could you update the description with some context, please? Curious.
