### ISSUE TITLE
[BUG] `stx-burn?` fails with ArithmeticUnderflow error

### ISSUE THREAD

**Issue by LNow** [hirosystems/clarinet#111]
Like the title says `stx-burn?` fails with ArithmeticUnderflow error.
`stx-liquid-supply` returns 0, therefore burning any amount of STX is impossible as it will always fail with underflow error.

**Comment by lgalabru** [comment]
Addressed with latest REPL, updated in https://github.com/hirosystems/clarinet/pull/116
