### ISSUE TITLE
LSP: go-to definition for contract-call?

### ISSUE THREAD

**Issue by friedger** [hirosystems/clarinet#1136]
**Is your feature request related to a problem? Please describe.**
As a developer, I would like to go to the definition of my function used in `(contract-call? .my-contract my-function....)`

**Describe the solution you'd like**
Same behaviour as for functions defined in the contract itself.

**Additional context**
Related issue #1094

**Comment by hugocaillard** [comment]
Thanks for reporting @friedger 
I just tested and it seems to be working well on my end between two contracts defined in a clarinet.toml.
Can you share a project where you think it should work but it doesn't?

If you are talking about `contract-call?` of a function defined in a contract in `requirements`, then this is a duplicated of #1094 (that you mentioned)

**Comment by hugocaillard** [comment]
@friedger 
I'll close this for now since it appears to be working on my end. Please re-open if you think there's a bug here
