### ISSUE TITLE
Better feedback message when test suite fails due to tests possibly filtered out

### ISSUE THREAD

**Issue by vicnicius** [hirosystems/clarinet#1138]
When running your test suite with `clarinet test`, if you have some tests with the `only` filter applied the test suite will fail. The behaviour is good since it can prevent devs from accidentally filtering out tests, but the error message could be improved.

Currently it just says `Test suite failed`

![image](https://github.com/hirosystems/clarinet/assets/1326024/3d0697aa-44a6-45dd-a7ff-830b61b560a5)

Ideally it should also say the reason `Test suite failed because the only filter is active and some tests could be implicitly filtered out`. Bonus points if you'd also show which tests have the `only` filter applied.

**Comment by hugocaillard** [comment]
Hey @vicnicius 
I agree that this isn't the most helpful message.
I think this is the default behavior in the framework we use (Deno test), but we will soon switch to Vitest by default (more context here https://github.com/hirosystems/clarinet/issues/1065) and `clarinet test` using Deno will be deprecated.

I'm therefore closing this issue. Let me know if you need more details about the new testing framework
