### ISSUE TITLE
Allow to choose esplora bitcoin api for clarinet integrate

### ISSUE THREAD

**Issue by friedger** [hirosystems/clarinet#1140]
**Is your feature request related to a problem? Please describe.**
As a app developer, I want to talk to the bitcoin [esplora API](https://github.com/Blockstream/esplora).

**Describe the solution you'd like**
Upload a docker image for esplora to quai.io that can be used in settings/Devnet.toml  

**Describe alternatives you've considered**
Rewrite my app to use bitcoinexplorer.org 

**Additional context**
Blocker for sBTC DR: https://github.com/stacks-network/sbtc/issues/106

**Comment by friedger** [comment]
Using `bitcoin_explorer_image_url = "blockstream/esplora:latest"` seems to be not enough.

**Comment by smcclellan** [comment]
@friedger Why are we linking to Esplora? Any additional context here would be helpful.

**Comment by friedger** [comment]
@smcclellan it was chosen for sBTC romeo setup to have an easier api

**Comment by stjepangolemac** [comment]
We've picked up esplora as it was one of the supported backends for [bdk](https://docs.rs/bdk/latest/bdk/). It was the easiest choice as we could connect to blockstream and not run any nodes locally.

I wouldn't say this is a hard requirement as we can also connect to RPC endpoints with some code changes.

**Comment by friedger** [comment]
Closing this one
