### ISSUE TITLE
Use the JS SDK for tests in Clarinet 2

### ISSUE THREAD

**Issue by hugocaillard** [hirosystems/clarinet#1143]
- [ ] When generating a new clarinet project or contract (with `clarinet new` or `clarinet contract new`), the boilerplate should use the `clarinet-sdk` instead of the legacy `deno` framework.
- [ ] Remove all mentions of `clarinet test` across the repo

**Comment by andresgalante** [comment]
I'll close this issue since it's marked as "done"
