### ISSUE TITLE
1.8.0 build failure

### ISSUE THREAD

**Issue by chenrui333** [hirosystems/clarinet#1153]
👋 trying to build the latest release, but run into some build issue. The error log is as below:

<details>
<summary>error build log</summary>

```
  error[E0080]: evaluation of constant value failed
      --> /Users/brew/Library/Caches/Homebrew/cargo_cache/registry/src/index.crates.io-6f17d22bba15001f/v8-0.47.1/src/isolate.rs:1216:3
       |
  1216 |   assert!(size_of::<TypeId>() == size_of::<u64>());
       |   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the evaluated program panicked at 'assertion failed: size_of::<TypeId>() == size_of::<u64>()', /Users/brew/Library/Caches/Homebrew/cargo_cache/registry/src/index.crates.io-6f17d22bba15001f/v8-0.47.1/src/isolate.rs:1216:3
       |
       = note: this error originates in the macro `assert` (in Nightly builds, run with -Z macro-backtrace for more info)
```

</details>

full build log, https://github.com/Homebrew/homebrew-core/actions/runs/6155050719/job/16701389502
relates to Homebrew/homebrew-core#142059

**Comment by chenrui333** [comment]
https://github.com/Homebrew/homebrew-core/pull/142106

**Comment by smcclellan** [comment]
@chenrui333 We are aware of this issue, the underlying problem being deno + homebrew. More context in [this comment](https://github.com/Homebrew/homebrew-core/pull/142106#issuecomment-1718318678). The fix will come as part of [this ticket](https://github.com/hirosystems/clarinet/issues/1065).
