### ISSUE TITLE
::get_costs command not working

### ISSUE THREAD

**Issue by Patotking12** [hirosystems/clarinet#1156]
**Describe the bug**
::get_costs command not returning information
::get_costs command needs an argument

**To Reproduce**
::get_costs (+ 1 2)
::get_costs command needs an argument

**Expected behavior**
Return a table with costs

**Screenshots**
<img width="1293" alt="Screenshot 2023-09-19 at 12 03 05" src="https://github.com/hirosystems/clarinet/assets/108552266/2284345c-46fb-46ea-8da9-309e3925b938">

**Environment (please complete the following information):**
macOS 13.5 (22G74)
clarinet 1.7.1

**Comment by binadamu-isiyoonekana** [comment]
Hi all,
  I'm newbie. I tried on latest `clarity-repl v2.11.2` on MacOS Sequoia 15.1 (Intel). It seems that it works (see screenshot below).

![Image](https://github.com/user-attachments/assets/5a500c6a-2b81-492f-899b-f27e6818c4b5)

**Comment by hugocaillard** [comment]
@binadamu-isiyoonekana 
right it seems to be fixed.
Thanks for reporting
