### ISSUE TITLE
Remove filesystem dependency from `initVM` 

### ISSUE THREAD

**Issue by lgalabru** [hirosystems/clarinet#1168]
@hugocaillard would it be useful to move from 

```javascript
vm.initSession(process.cwd(), manifestPath);
```

to something like
```javascript
vm.initSession(readManifest(process.cwd(), manifestPath)); // or equivalent
```
?

**Comment by hugocaillard** [comment]
@lgalabru we only pass the path as a string (well, two strings) to the wasm SDK, which will read the file. 

We also [pass the VFS (virtual file system) to the wasm SDK](https://github.com/hirosystems/clarinet/blob/90095061037e0abfe1043443d8a4e5e5bc3d2dff/components/clarinet-sdk/src-ts/index.ts#L218C35-L218C38), which in the case is a using node:fs but using the same interface as the VSCode VFS, and could theoretically be anything else (if a front end app - the platform? - implements some custom fs methods).

So on the rust side we're good, build the JS ârt and webpack build could be slightly improved in the future
