### ISSUE TITLE
Post-installation instructions

### ISSUE THREAD

**Issue by agraebe** [hirosystems/clarinet#117]
As per our previous conversation, it would be great to display instructions for developers post installation (or broadly speaking, post exeuction of a command). This will help developers get oriented and identify what next steps are recommended and/or possible. 

Here are some examples of other CLIs:

<img width="447" alt="Screen Shot 2021-09-14 at 5 36 03 PM" src="https://user-images.githubusercontent.com/1671228/133351710-1a7a8898-24dc-4173-92a5-6817438117db.png">

<img width="711" alt="Screen Shot 2021-09-14 at 5 32 18 PM" src="https://user-images.githubusercontent.com/1671228/133351720-262e5fd7-a695-44e4-86fc-d162bd5a2849.png">

<img width="549" alt="Screen Shot 2021-09-14 at 5 29 49 PM" src="https://user-images.githubusercontent.com/1671228/133351731-cf60c61a-910e-4d0f-b520-22eefa38521a.png">

<img width="643" alt="Screen Shot 2021-09-14 at 5 28 10 PM" src="https://user-images.githubusercontent.com/1671228/133351743-fa7bbe5e-26c6-4dfa-8e61-d439eab2b296.png">

**Comment by lgalabru** [comment]
Addressed with latest
