### ISSUE TITLE
Improve CLI command help instructions

### ISSUE THREAD

**Issue by agraebe** [hirosystems/clarinet#118]
The current help is fairly basic and could benefit from a revision. This file is most relevant: https://github.com/hirosystems/clarinet/blob/21b91e5241f188f9c7681c793f0af812ee21ff3d/src/frontend/cli.rs#L29

@pgray-hiro do you think we could jam on the instructions we would like to see here?

**Comment by pgray-hiro** [comment]
At the minimum I think each command and subcommand needs an `.about` string with clap and each arg needs a `.help` string. I would jump in and try to help but I don't know Rust well enough, and this code is different enough from the publicly available `clap` examples that I can't figure out where to put these strings.

@lgalabru could you show an example of how to insert these help strings into your code?
