### ISSUE TITLE
Prevent clarinet test from scanning all files with test in the whole repo.

### ISSUE THREAD

**Issue by aviculturist** [hirosystems/clarinet#119]
Currently I have to specifically name the directly like clarinet test tests/ to get just my tests to run, otherwise I get nothing but failures like Uncaught ReferenceError: require is not defined.

I'd like to be able to specify a specific directory to restrict clarinet to, then I could write other tests nearby that use other frameworks (like clarigen) that won't interfere.

**Comment by lgalabru** [comment]
Addressed with https://github.com/hirosystems/clarinet/pull/116
