### ISSUE TITLE
clarinet test runs even though contracts contain syntax errors

### ISSUE THREAD

**Issue by friedger** [hirosystems/clarinet#1191]
**Describe the bug**
As described in https://github.com/stacks-network/sbtc/pull/247#issuecomment-1751373997
the contract contains a syntax error but `clarinet test` reports that all tests succeeded. 

**To Reproduce**

1. Checkout https://github.com/stacks-network/sbtc/commit/929250b2622fc25e8dbf0ea001cada4f54cee6b4 
2. cd romeo/asset-contract
3. clarinet check shows the syntax error
4. run ./scripts/tests.sh
5. See that all 32 tests passed.

**Expected behavior**
Unit tests should have failed.

**Comment by lgalabru** [comment]
Thanks @friedger! The testsuite should definitely error if the contracts are invalid. We will address this in future versions!

**Comment by hugocaillard** [comment]
To clarify, will make sure that this behavior is handled in the new testing framework with the clarinet-sdk, but `clarinet test` won't be fixed.
Let me know if that makes sense @friedger

**Comment by friedger** [comment]
Makes sense.
