### ISSUE TITLE
clarity check does not error on unused expression

### ISSUE THREAD

**Issue by unclemantis** [hirosystems/clarinet#122]
```
These 2 blocks of code do not return errors when running clarity check.
(define-public (foo (id int))
  (bar id)
)
(define-public (foo (id int))
  (bar)
)
```
```
Error should return on above second function. I had to run a test on foo to discover that bar needed id passed.

Would be nice.
```

**Comment by LNow** [comment]
It is a Clarity VM bug discovered few months ago: https://github.com/blockstack/stacks-blockchain/issues/2683

**Comment by lgalabru** [comment]
@LNow correct. Fixing this bug is consensus bearing. Fixing this issue at the blockchain level, will fix it here.
Considering this issue as a duplicate, will close.
