### ISSUE TITLE
VSCE unable to resolve dependency associated to constant when CLI can

### ISSUE THREAD

**Issue by lgalabru** [hirosystems/clarinet#1224]
![Screenshot 2023-10-24 at 15 27 34](https://github.com/hirosystems/clarinet/assets/87777/2a6d727f-6cf8-4763-83e9-9c5b4648fb85)

**Comment by hugocaillard** [comment]
Fixed in #1205 
I need to release an update of the extension

**Comment by hugocaillard** [comment]
Release in https://github.com/hirosystems/clarinet/pull/1230
