### ISSUE TITLE
Define contract from two files

### ISSUE THREAD

**Issue by friedger** [hirosystems/clarinet#1267]
**Is your feature request related to a problem? Please describe.**
pox-4 contract is the concatenation of pox-4.clar and pox-mainnet.clar or pox-testnet.clar
There is currently no way to define this in Clarinet.toml

**Describe the solution you'd like**
It would be nice to use a list of path and the resulting contract code consists of the concatenation of the listed files.

**Describe alternatives you've considered**
Currently, we duplicate the code and add unit tests to ensure the the two copies stay in sync

**Additional context**
https://github.com/stacks-network/stacks-core/pull/4094#discussion_r1407961951

**Comment by hugocaillard** [comment]
@friedger Since it's an edge case that will only be used for pox contracts (and maybe other boot contracts), are we sure that pox-4 will be tested with clarinet?

Also, since this is only for boot contracts, I wonder if we want to hard code this logic for boot contracts or if we want to let anyone do it in the Clarinet.toml, which might a bit weird I guess 🤔

**Comment by friedger** [comment]
@hugocaillard I have seen different cases where changes needs to be made between testnet and mainnet. For example, all contract that reference a SIP trait or when mock/debug functions are used. 

It can help improve the process of testnet mainnet switching in general.

**Comment by friedger** [comment]
For traits, the referenced contracts are different like SP123.sip-10-trait vs ST987.trait-sip10

The deployed code will be different.

Your suggestion would be a great solution.

**Comment by hugocaillard** [comment]
@friedger The recommended way is to handle it with clarinet is to add `SP123.sip-10-trait` as a requirements.
When deploying on testnet, a sip-10-trait will be deployed for you. And when deploying on mainnet, it will use `SP123.sip-10-trait`

**Comment by hugocaillard** [comment]
Hey @friedger. I'm closing for now feel free to re-open at any point if needed
