### ISSUE TITLE
Clarinet should not overwrite existing contracts without any warnings.

### ISSUE THREAD

**Issue by LNow** [hirosystems/clarinet#13]
Assuming that I have a contract `super-important-contract.clar` already in place.
When I call `clarinet generate contract super-important-contract` clarinet should detect that contract with exactly the same name already exist and ask user if it should be replaced with empty contract or not instead of overwriting it without any warning.

**Comment by lgalabru** [comment]
Thanks for reporting this issue @LNow, will fix!

**Comment by lgalabru** [comment]
Addressed with latest
