### ISSUE TITLE
`clarinet test` requires test file to include `_test` in name

### ISSUE THREAD

**Issue by JMKJR** [hirosystems/clarinet#132]
When adding a new test file to your `clarinet` project, if the test file name does not end with `_test` then `clarinet test` will fail with error `No matching test modules found`. Normally test frameworks target all files in a folder like "tests" for inclusion and ignore filename conventions. Assuming there is good reason to force the `_test` naming heuristic, could we at least update the documentation to caution users that this convention is required?

**Comment by obycode** [comment]
This behavior comes from deno, so we may not want to modify this.

https://github.com/hirosystems/deno/blob/82e283d50231f13f3ff4c54e3c208fbecc075366/cli/tools/test_runner.rs#L212-L234
```rs
pub fn is_supported(p: &Path) -> bool {
  use std::path::Component;
  if let Some(Component::Normal(basename_os_str)) = p.components().next_back() {
    let basename = basename_os_str.to_string_lossy();
    basename.ends_with("_test.ts")
      || basename.ends_with("_test.tsx")
      || basename.ends_with("_test.js")
      || basename.ends_with("_test.mjs")
      || basename.ends_with("_test.jsx")
      || basename.ends_with(".test.ts")
      || basename.ends_with(".test.tsx")
      || basename.ends_with(".test.js")
      || basename.ends_with(".test.mjs")
      || basename.ends_with(".test.jsx")
      || basename == "test.ts"
      || basename == "test.tsx"
      || basename == "test.js"
      || basename == "test.mjs"
      || basename == "test.jsx"
  } else {
    false
  }
}
```

**Comment by unclemantis** [comment]
I just use clarinet contract new and let the that build and modify the toml file and contracts and tests folders..

Maybe I am not thinking outside the box. MAYBE developers are creating different test files based on a wide range of feature testing for a single contract.

**Comment by obycode** [comment]
Hi @JMKJR. I added some additional documentation in [this PR](https://github.com/hirosystems/clarinet/pull/274/files). Please let me know if you think anything else is missing to resolve this issue. Thanks!

**Comment by lgalabru** [comment]
Closing now, feel free to re-open if this is a blocker!
