### ISSUE TITLE
UTF-8 with Unicode isn't working in complex types (tuple, lists etc)

### ISSUE THREAD

**Issue by ameeratgithub** [hirosystems/clarinet#1323]
Unicode characters, like `\u{ff}`, don't work in complex types, like lists and tuples. For instance this would work fine in clarinet console

```
(list u"ff")
```

but as soon as you put unicode character, it won't work. Following example won't return any result

```
(list u"\u{ff}")
```

**To Reproduce**
1. Open terminal
2. Run `clarinet console`
3. Execute `(list u"\u{ff}")`

**Expected behavior**
Should return result (or panic if input is not correct).

You can see the following image

![image](https://github.com/hirosystems/clarinet/assets/55062550/44065175-c993-4e6e-954e-57d6b00babc9)

**Comment by hugocaillard** [comment]
Thanks for reporting @ameeratgithub 
It has been fixed and will be part of the next clarinet release (this week)
