### ISSUE TITLE
fix hint messaging in clarinet cli pointing to old docs page

### ISSUE THREAD

**Issue by ryanwaits** [hirosystems/clarinet#1333]
old url: https://docs.hiro.so/clarinet/how-to-guides/how-to-run-integration-environment
new url: https://docs.hiro.so/clarinet/guides/how-to-run-integration-environment

![Image](https://github.com/hirosystems/clarinet/assets/3207017/15eba643-a772-44d5-a583-1c6518a4906b)

**Comment by ryanwaits** [comment]
these changes depend on [this pr](https://github.com/hirosystems/docs/pull/602)

**Comment by tippenein** [comment]
#1328  has this fix included

**Comment by hugocaillard** [comment]
Fixes with #1328 
Thx @tippenein
