### ISSUE TITLE
invalid signature for method regarding trait's specification

### ISSUE THREAD

**Issue by whoabuddy** [hirosystems/clarinet#1353]
**Describe the bug**

I want to create a trait for the `stacks-m2m` contracts, but I keep getting an error on three functions.

If I comment them out it works as expected, and when I run `clarinet check` I get the following error as an example:

`error: invalid signature for method 'add-resource' regarding trait's specification <stacks-m2m-trait-v1>`

**To Reproduce**

1. Run `clarinet check` [against the lastest code](https://github.com/stacks-m2m/contracts)
2. See error

There are three trait signatures that cause the errors:

```clarity
(define-trait stacks-m2m-trait-v1
  (
    (set-payment-address (principal principal) (response bool uint)) ;; works
    (add-resource ((string-utf8 50) (string-utf8 255) uint) (response bool uint)) ;; error
    (delete-resource (uint) (response bool uint)) ;; works
    (delete-resource-by-name ((string-utf8 50)) (response bool uint)) ;; works
    (pay-invoice (uint (optional (buff 34))) (response bool uint)) ;; error
    (pay-invoice-by-resource-name ((string-utf8 50) (optional (buff 34))) (response bool uint))  ;; error
  )
)
```

These are the related function signatures:

```clarity
(define-public (add-resource (name (string-utf8 50)) (description (string-utf8 255)) (price uint)))
(define-public (pay-invoice (resourceIndex uint) (memo (optional (buff 34)))))
(define-public (pay-invoice-by-resource-name (name (string-utf8 50)) (memo (optional (buff 34)))))
```

**Expected behavior**

The traits should match the function signature. I'm pretty sure they do and have compared to other implementations and run through some GPT sessions. The error messages aren't helpful in troubleshooting the actual problem, so not sure where to go from here.

**Screenshots**

It'd be great if this highlighted the impl-trait line instead of the start of the file:
![image](https://github.com/hirosystems/clarinet/assets/9038904/82b41089-3ddb-4cd9-a1b3-57125c0cf10e)

![image](https://github.com/hirosystems/clarinet/assets/9038904/da3c9964-6373-4482-9cd3-f1beecdb9805)

**Additional context**

If the error were giving me some more detail on *what was wrong* that'd be really helpful - at this point I'm not sure where I went wrong!

**Comment by hugocaillard** [comment]
Thanks for reporting this issue, I'll have a look now.
Regarding the highlighted line being wrong, this is an issue that we have at the type-checker level (from the clarity-vm in stacks-core repo). The fix has been delayed because of other priorities, maybe we could consider finding a workaround at the clarinet level in the meantime

**Comment by hugocaillard** [comment]
@whoabuddy 
The trait defines that `add-resource` should return `(response bool uint)` but the contract return `(ok new-count)` which is `(response uint uint)`

Same for `pay-invoice`  and `pay-invoice-by-resource-name`

I'm closing this issue ofr now, feel free to re-open if needed

**Comment by whoabuddy** [comment]
I knew it was something small - thank you!!
