### ISSUE TITLE
TypeError: Object.entries(...).toSorted is not a function when using Node.js v18.15

### ISSUE THREAD

**Issue by ECBSJ** [hirosystems/clarinet#1354]
When running the code snippet from [Unit Test for `Counter` Example](https://docs.hiro.so/clarinet/guides/test-contract-with-clarinet-sdk#unit-tests-for-counter-example) on Nodejs v18.15, the below error is thrown:

![image](https://github.com/hirosystems/clarinet/assets/61910547/bc07ed76-e47e-4aa2-a32b-36b54df5aa6a)

It is thrown from the `expect(printEvent.data.value).toBeTuple()` method from the code snippet. Upon further inspection of the definition in the `clarityValuesMatchers.ts` file, the `toBeTuple()` method (ln 345) is using [`Object.entries().toSorted`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypedArray/toSorted) method which is only supported in Nodejs v20.

![image](https://github.com/hirosystems/clarinet/assets/61910547/e921a585-acf1-4535-b4e9-8499167df5c3)

I changed the two `.toSorted` calls to `.sort` methods and the test for "sends a print event" passes.

![image](https://github.com/hirosystems/clarinet/assets/61910547/0bd19af9-ad0e-40a8-9152-2897a4774471)
![image](https://github.com/hirosystems/clarinet/assets/61910547/86e0c6ee-c23e-4512-bc5a-63bf5216c64f)

**Environment**
 - Nodejs v18.15
 - Clarinet v2.2.1

**Comment by hugocaillard** [comment]
Nice catch @ECBSJ, thanks for reporting and for the investigation.
I'll fix it to support older Node.js version.
But out of curiosity, do consider upgrading to Node 20 (which the current LTS) or is there anything preventing you from doing so?

**Comment by ECBSJ** [comment]
No reason in particular for not upgrading. Will consider upgrading though.

**Comment by hugocaillard** [comment]
Will be fixed at the stacks.js level so that we don't have to handle properties sorting at the clarinet level
https://github.com/hirosystems/stacks.js/pull/1631

Will update clarinet and close this PR once the new release of stacks.js is available
