### ISSUE TITLE
Costs and coverage reports are blank

### ISSUE THREAD

**Issue by whoabuddy** [hirosystems/clarinet#1359]
**Describe the bug**

When I run `npm test:report` it passes the commands to Clarinet, but the resulting files are empty.

**To Reproduce**

1. Go to https://github.com/stacks-m2m/contracts
2. Run `npm test:report`
3. View resulting `costs-reports.json` and `lcov.info`

**Expected behavior**

To receive cost and coverage data.

**Environment (please complete the following information):**

 - OS (version): Linux Mint
 - Docker version: Docker version 25.0.3, build 4debf41
 - Clarinet version: clarinet 2.2.0

**Additional context**

package.json:
```json
{
  "name": "stacks-m2m-contracts",
  "description": "Machine-payable transactions on Stacks.",
  "author": "",
  "version": "0.0.2",
  "license": "MIT",
  "type": "module",
  "private": true,
  "scripts": {
    "test": "vitest run",
    "test:report": "vitest run -- --coverage --costs",
    "test:watch": "chokidar \"tests/**/*.ts\" \"contracts/**/*.clar\" -c \"npm run test:report\""
  },
  "dependencies": {
    "@hirosystems/clarinet-sdk": "^1.2.0",
    "@stacks/transactions": "^6.11.2",
    "chokidar-cli": "^3.0.0",
    "typescript": "^5.3.3",
    "vite": "^5.0.12",
    "vitest": "^1.2.1",
    "vitest-environment-clarinet": "^1.1.0"
  }
}
```

`lcov.info` has a bunch of blank lines
![image](https://github.com/hirosystems/clarinet/assets/9038904/e7560a7f-d1b4-4dcb-943b-ccb304ab612f)

`costs-reports.json` is an empty array: `[]`

**Comment by hugocaillard** [comment]
Hey @whoabuddy 
The thing is that you don't need to call `initSimnet` by yourself, but instead, use the globally available `simnet` object. This is what allows us to keep track of the costs and coverage.

So if you remove all of the `import { initSimnet } from "@hirosystems/clarinet-sdk";
`and `const simnet = await initSimnet();`, it should work as expected 👍 

I'm afraid this could be a common mistake though. I'm curious, why did you `const simnet = await initSimnet();` in the first place? Is there a place in the doc where you saw it?

Thx

**Comment by whoabuddy** [comment]
Can confirm this is working now after taking out the related `simnet` references, also removed `async ()` on the functions since it doesn't seem to have an effect.

For where it came from - found it here in the docs:
https://docs.hiro.so/clarinet/guides/clarinet-js-sdk

![image](https://github.com/hirosystems/clarinet/assets/9038904/f4c017ed-4d98-4b5a-a363-6bac09133e97)

Things seem to be working correctly although now it only shows me the test file name and not the list of tests underneath.

**Comment by whoabuddy** [comment]
Also can confirm that `npm run test:report` now generates the costs-reports.json and lcov.info files :clap: 

Feel free to close from my side!

**Comment by hugocaillard** [comment]
Ok I see. The docs explains how to use the simnet in general. But in the vitest environment it's slightly different (especially, there's this simnet object available locally)
I'll see how I can clarify that in the docs

> now it only shows me the test file name and not the list of tests underneath

Weird. I think this part is only handled by Vitest. It'll show the detailed view if there errors or warnings (like slow tests) (or if there only 1 file), but it shows the compact view when there is nothing particular to report. Maybe you can customize that
