### ISSUE TITLE
Update stacks-node and add stacks-signer

### ISSUE THREAD

**Issue by hugocaillard** [hirosystems/clarinet#1379]
- update stacks-node image
- update stack-stx (new arguments in pox-4 for stack-stx and extend)
- add the signer image to the devnet

**Comment by sabbyanandan** [comment]
@hugocaillard: It is probably too early right now, but when the time is right, it'd be good to get a sense of the Docker daemon's compute requirements (i.e., what is a reasonable CPU, disk, and memory defaults?), including the additional resources (for instance, a new "signer image") that need to be spun up. We can add/update the pre-requisite section in docs/README. 

In the Platform, we will automatically apply and handle the dynamic allocation of new resource requirements for each user.
