### ISSUE TITLE
Allow dependency on deployed contracts

### ISSUE THREAD

**Issue by friedger** [hirosystems/clarinet#14]
It would be nice to declare a deployed contract like this

```
[contracts.sip-009]
path = "https://stacks-node-api.blockstack.org/v2/contracts/source/SP1JSH2FPE8BWNTP228YZ1AZZ0HE0064PS6RXRAY4/nft-trait"
depends_on = []
```
and then use it as a dependency

**Comment by lgalabru** [comment]
`0.9.3` is introducing an experimental version of this feature.
You can now do: 
```
$ clarinet contract requirement SP1JSH2FPE8BWNTP228YZ1AZZ0HE0064PS6RXRAY4.nft-trait
```

It is probably fine for hacking and toying with with `clarity console`, but if you have a lot of tests, it could be annoying - the "required contracts" are not locally cached at the moment.

**Comment by friedger** [comment]
requirement feature implemented
