### ISSUE TITLE
Unable to use the 'replace-at?' function in contract

### ISSUE THREAD

**Issue by JoE11-y** [hirosystems/clarinet#1407]
**Describe the bug**

Unable to use the replace-at? function in a contract, but in clarinet console it works fine. Is there anything I'm doing wrong?

**To Reproduce**

```
(define-private (test) 
  (ok (replace-at? u"ab" u1 u"c"))
)
```
See error
```
error: use of unresolved function 'replace-at?'
--> contracts/locker.clar:116:4
  (ok (replace-at? u"ab" u1 u"c"))
   ^~
  (ok (replace-at? u"ab" u1 u"c"))
```

**Expected behavior**

A call made on the clarinet console

```
>> (replace-at? u"ab" u1 u"c")
(some u"ac")
```

**Screenshots**
If applicable, add screenshots or consol.log to help explain your problem.

**Environment (please complete the following information):**
 - OS (version): [e.g. debian 12]
 - Docker version [e.g. 24.0.4]
 - Clarinet version [e.g. 24.0.6] - Please use the latest version

**Comment by hugocaillard** [comment]
Hello @JoE11-y 

It's probably that in your manifest, the clarity version is too low. Because `replace-at?` was introduced in Clarity 2. See an example here: 
https://github.com/hirosystems/clarity-starter/blob/main/Clarinet.toml#L9-L12

**Comment by JoE11-y** [comment]
Whoa man, thanks. 
It solved that issue and a bunch of others. 🫡
