### ISSUE TITLE
Have a way to fork mainnet

### ISSUE THREAD

**Issue by OxMarco** [hirosystems/clarinet#1439]
It would be nice to have a way to fork the status of a network, in order to run "stateful" tests.
This issue is particularly relevant when testing contracts that interact with other primitives, like lending protocols or oracles, where setting up the state manually in a test is not trivial.

**Comment by lgalabru** [comment]
Related: https://github.com/lgalabru/stacks-core/pull/1

**Comment by hugocaillard** [comment]
Thanks for surfacing this issue @OxMarco.
I'm closing this issue in favor of a more formal one: #1503.

Please subscribe to it to be notified about the progress
