### ISSUE TITLE
Incorrect stx costs for deployment

### ISSUE THREAD

**Issue by friedger** [hirosystems/clarinet#1447]
**Describe the bug**
When applying a deployment, the costs are shown as 0.001 STX instead of 0.1 STX

**To Reproduce**
1. Create a deployment
2. Provide costs of 100000 uSTX
3. Apply deployment and see preview

**Expected behavior**
Costs are converted correctly from uSTX to STX

**Screenshots**
![image](https://github.com/hirosystems/clarinet/assets/1449049/f74b2b6d-edec-4bdc-a62b-45dc1d70be40)

**Comment by hugocaillard** [comment]
Good catch, thanks for reporting @friedger

**Comment by hugocaillard** [comment]
Fixed by #1563
Released in 2.9.0
