### ISSUE TITLE
Use Stacks node v2.5 for the local testnet

### ISSUE THREAD

**Issue by OxMarco** [hirosystems/clarinet#1458]
It seems `clarinet integrate` uses a year-old version of the Stacks node API 

* current version that comes as default in the *Devnet.toml* file
`quay.io/hirosystems/stacks-node:devnet-2.4.0.0.0`

* oldest version 
`quay.io/hirosystems/stacks-node:devnet-2.5` 
OR
`blockstack/stacks-blockchain:2.5.0.0.3`

I tried updating the image but the Stacks and bitcoin node are stuck in the "booting" phase for days, something that doesn't happen when using the v2.4.

**Comment by radicleart** [comment]
> It seems `clarinet integrate` uses a year-old version of the Stacks node API
> 
> *

What does `clarinet --version` report ? 

Version 2.6 boot up two signers so must be using 2.5.

```
6d7a1e8208c8   Up 4 hours   stacks-signer-2.aibtcdev-smart-contracts.devnet
37e54f6dd6a0   Up 4 hours   stacks-signer-1.aibtcdev-smart-contracts.devnet
943dd5e9ab9b   Up 4 hours   stacks-node.aibtcdev-smart-contracts.devnet        0.0.0.0:20443-20444->20443-20444/tcp
```

**Comment by hugocaillard** [comment]
@OxMarco Does the comment above answers your question?
I'm closing for now, feel free to re-open of you still experience this issue
