### ISSUE TITLE
Improve deploying to mainnet experience

### ISSUE THREAD

**Issue by pradel** [hirosystems/clarinet#149]
I saw that deploying to mainnet is not possible at the moment, but the current version makes it really hard to understand what's going on. I was able to find in the clarity source code that it was not supported. From this message it's not clear at all, I first thought I did something wrong.

![Capture_decran_2021-11-01_a_10 15 28](https://user-images.githubusercontent.com/5749437/139659560-ea78df07-3cc6-4855-b012-7501baf53d6c.png)

In case the user is using the `--mainnet` option a message saying that it's not supported should be printed. Or removing the option for now could also work.

**Comment by lgalabru** [comment]
Will look into it, thank you for opening this issue @pradel!
