### ISSUE TITLE
running clarinet in the background

### ISSUE THREAD

**Issue by FidelVe** [hirosystems/clarinet#1502]
Is it possible to run clarinet in the background? if not, is there a docker compose file that I can use to run all the containers easily and then shut them down with a command inside a makefile for example?

EDIT:

Adding more context, im trying to run a devnet so what I want is to run `clarinet devnet start` in the background, or run the required containers with a docker compose file and then be able to shut them down at my discretion later.

**Comment by hugocaillard** [comment]
@FidelVe 
You can run any command in the background by adding `&` at the end. For the devnet, you can add `--no-dashboard` 
So you can do
```sh
clarinet devnet start --no-dashboard &
```

To gracefully shutdown the process, you should be able to send a sigterm, but we might not handle it properly: https://github.com/hirosystems/clarinet/issues/1391. (You can still do it by shutting down the containers with docker, although it's not ideal.
Will look into the sigterm issue, I suggest you subscribe to it

**Comment by hugocaillard** [comment]
@FidelVe I assume you are willing to run the devnet on a server right?
If so, I'd like to know more about your use case and see how we can help supporting this use case. (let me know if you prefer to talk about by mail or find me on the Stacks Discord in the Clarinet channel)

**Comment by FidelVe** [comment]
thanks for the reply.

I previously tried sending clarinet to the background using these commands without success

```
 clarinet devnet start &
 clarinet devnet start > output.log 2>&1 &
 nohup clarinet devnet start > output.log 2>&1 &
 setsid clarinet devnet start > output.log 2>&1 &
```

they all fail to create the docker containers the only thing that gets created is the docker network

I'll try now using the --no-dashboard flag

I'll contact you on discord 👍
