### ISSUE TITLE
Override fee estimate for command-line contract deploy

### ISSUE THREAD

**Issue by pgray-hiro** [hirosystems/clarinet#151]
When deploying to testnet using Clarinet, I regularly received errors that the fee provided was too low. I ultimately had to switch to the Stacks CLI because it had the ability to manually specify fees for the deploy transaction. It would be nice to have such a flag in Clarinet, so when the fee estimation is too low a user can manually override.

**Comment by lgalabru** [comment]
In the latest version of Clarinet, in your `Testnet.toml` / `Mainnet.toml` you can set:
```toml
[network]
...
deployment_fee_rate = 100
```
