### ISSUE TITLE
clarinet fails unexpectedly on windows

### ISSUE THREAD

**Issue by Godtide** [hirosystems/clarinet#152]
clarinet check does not transpile more than one line of code in .clar on windows machine

**Comment by lgalabru** [comment]
Clarinet does not transpile anything, on any platform :)
Could you maybe unpack what are the steps that you're doing and what are you seeing?
If windows, you should make sure that you're using `LF` as an end line sequence (instead of `CRLF` - default on Windows).

**Comment by Godtide** [comment]
Hey @lgalabru thank you for response, I mean cannot use **clarinet check** on windows for more than more line. I get an ERL... error that usually comes with versioning, I changed OS because I thought Ubuntu was the answer, and may not be able to continue troubleshooting with you on this
