### ISSUE TITLE
Build issues installing on ubuntu 18.0.04

### ISSUE THREAD

**Issue by Godtide** [hirosystems/clarinet#153]
**https://github.com/hirosystems/clarinet#install-from-a-pre-built-binary**

`rustc --explain E0658`.
error: could not compile `clap``

`
An unstable feature was used.

Erroneous code example:

```
#[repr(u128)] // error: use of unstable library feature 'repr128'
enum Foo {
    Bar(u64),
}
```
:`

**https://github.com/hirosystems/clarinet#install-from-source-using-cargo**

`Running `rustc --crate-name clap --edition=2018 /home/tide/.cargo/registry/src/github.com-1ecc6299db9ec823/clap-3.0.0-beta.4/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi --crate-type lib --emit=dep-info,metadata,link -C opt-level=3 -C embed-bitcode=no --cfg 'feature="atty"' --cfg 'feature="cargo"' --cfg 'feature="clap_derive"' --cfg 'feature="color"' --cfg 'feature="default"' --cfg 'feature="derive"' --cfg 'feature="env"' --cfg 'feature="lazy_static"' --cfg 'feature="std"' --cfg 'feature="strsim"' --cfg 'feature="suggestions"' --cfg 'feature="termcolor"' --cfg 'feature="unicode_help"' -C metadata=a3d855505ac51ae0 -C extra-filename=-a3d855505ac51ae0 --out-dir /home/tide/clarinet/target/release/deps -L dependency=/home/tide/clarinet/target/release/deps --extern atty=/home/tide/clarinet/target/release/deps/libatty-8c49f159338d06e8.rmeta --extern bitflags=/home/tide/clarinet/target/release/deps/libbitflags-b775ec35c0260123.rmeta --extern clap_derive=/home/tide/clarinet/target/release/deps/libclap_derive-f3c37e1a2ef73567.so --extern indexmap=/home/tide/clarinet/target/release/deps/libindexmap-171222540c838c94.rmeta --extern lazy_static=/home/tide/clarinet/target/release/deps/liblazy_static-0fdabdf0c41b00c5.rmeta --extern os_str_bytes=/home/tide/clarinet/target/release/deps/libos_str_bytes-a6573fe882146b4a.rmeta --extern strsim=/home/tide/clarinet/target/release/deps/libstrsim-4fb4cd4fa533a7a3.rmeta --extern termcolor=/home/tide/clarinet/target/release/deps/libtermcolor-d133e93d52de74af.rmeta --extern textwrap=/home/tide/clarinet/target/release/deps/libtextwrap-8e74302250090374.rmeta --extern vec_map=/home/tide/clarinet/target/release/deps/libvec_map-1df9fa7a81a4a8dc.rmeta --cap-lints allow`
   Compiling mio v0.7.13
   Compiling serde_json v1.0.64
   Compiling want v0.3.0
     Running `rustc --crate-name mio --edition=2018 /home/tide/.cargo/registry/src/github.com-1ecc6299db9ec823/mio-0.7.13/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts --crate-type lib --emit=dep-info,metadata,link -C embed-bitcode=no -C debug-assertions=off --cfg 'feature="default"' --cfg 'feature="net"' --cfg 'feature="os-ext"' --cfg 'feature="os-poll"' --cfg 'feature="os-util"' --cfg 'feature="tcp"' --cfg 'feature="udp"' --cfg 'feature="uds"' -C metadata=a75831e75f361853 -C extra-filename=-a75831e75f361853 --out-dir /home/tide/clarinet/target/release/deps -L dependency=/home/tide/clarinet/target/release/deps --extern libc=/home/tide/clarinet/target/release/deps/liblibc-9fd42d2469b89693.rmeta --extern log=/home/tide/clarinet/target/release/deps/liblog-01004d3279b4466d.rmeta --cap-lints allow`
     Running `rustc --crate-name serde_json --edition=2018 /home/tide/.cargo/registry/src/github.com-1ecc6299db9ec823/serde_json-1.0.64/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts --crate-type lib --emit=dep-info,metadata,link -C embed-bitcode=no -C debug-assertions=off --cfg 'feature="default"' --cfg 'feature="indexmap"' --cfg 'feature="preserve_order"' --cfg 'feature="std"' --cfg 'feature="unbounded_depth"' -C metadata=ec7c9c4c1e43e808 -C extra-filename=-ec7c9c4c1e43e808 --out-dir /home/tide/clarinet/target/release/deps -L dependency=/home/tide/clarinet/target/release/deps --extern indexmap=/home/tide/clarinet/target/release/deps/libindexmap-be3b4506c7a9095e.rmeta --extern itoa=/home/tide/clarinet/target/release/deps/libitoa-1099de878ea4ad82.rmeta --extern ryu=/home/tide/clarinet/target/release/deps/libryu-0e27f017f356a76f.rmeta --extern serde=/home/tide/clarinet/target/release/deps/libserde-3891062f952432cb.rmeta --cap-lints allow --cfg limb_width_64`
     Running `rustc --crate-name want --edition=2018 /home/tide/.cargo/registry/src/github.com-1ecc6299db9ec823/want-0.3.0/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi --crate-type lib --emit=dep-info,metadata,link -C embed-bitcode=no -C debug-assertions=off -C metadata=df894cb5aeaf308a -C extra-filename=-df894cb5aeaf308a --out-dir /home/tide/clarinet/target/release/deps -L dependency=/home/tide/clarinet/target/release/deps --extern log=/home/tide/clarinet/target/release/deps/liblog-01004d3279b4466d.rmeta --extern try_lock=/home/tide/clarinet/target/release/deps/libtry_lock-c72e816040b7a2bc.rmeta --cap-lints allow`
error[E0658]: arbitrary expressions in key-value attributes are unstable
 --> /home/tide/.cargo/registry/src/github.com-1ecc6299db9ec823/clap-3.0.0-beta.4/src/lib.rs:8:10
  |
8 | #![doc = include_str!("../README.md")]
  |          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |
  = note: see issue #78835 <https://github.com/rust-lang/rust/issues/78835> for more information

   Compiling rustls v0.19.1
     Running `rustc --crate-name rustls --edition=2018 /home/tide/.cargo/registry/src/github.com-1ecc6299db9ec823/rustls-0.19.1/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts --crate-type lib --emit=dep-info,metadata,link -C embed-bitcode=no -C debug-assertions=off --cfg 'feature="dangerous_configuration"' --cfg 'feature="default"' --cfg 'feature="log"' --cfg 'feature="logging"' -C metadata=875c12b07df253d7 -C extra-filename=-875c12b07df253d7 --out-dir /home/tide/clarinet/target/release/deps -L dependency=/home/tide/clarinet/target/release/deps --extern base64=/home/tide/clarinet/target/release/deps/libbase64-ce9856b257ef51f4.rmeta --extern log=/home/tide/clarinet/target/release/deps/liblog-01004d3279b4466d.rmeta --extern ring=/home/tide/clarinet/target/release/deps/libring-9ee7bf99b258a6e8.rmeta --extern sct=/home/tide/clarinet/target/release/deps/libsct-bee090fe8308d550.rmeta --extern webpki=/home/tide/clarinet/target/release/deps/libwebpki-53e09e14cd026f55.rmeta --cap-lints allow -L native=/home/tide/clarinet/target/release/build/ring-6d4573c55f06cd5a/out`
error[E0658]: use of unstable library feature 'osstring_ascii'
   --> /home/tide/.cargo/registry/src/github.com-1ecc6299db9ec823/clap-3.0.0-beta.4/src/parse/matches/matched_arg.rs:130:19
    |
130 |                 v.eq_ignore_ascii_case(val)
    |                   ^^^^^^^^^^^^^^^^^^^^
    |
    = note: see issue #70516 <https://github.com/rust-lang/rust/issues/70516> for more information

   Compiling native-tls v0.2.7
     Running `rustc --crate-name native_tls /home/tide/.cargo/registry/src/github.com-1ecc6299db9ec823/native-tls-0.2.7/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts --crate-type lib --emit=dep-info,metadata,link -C embed-bitcode=no -C debug-assertions=off -C metadata=cf095aa156455248 -C extra-filename=-cf095aa156455248 --out-dir /home/tide/clarinet/target/release/deps -L dependency=/home/tide/clarinet/target/release/deps --extern log=/home/tide/clarinet/target/release/deps/liblog-01004d3279b4466d.rmeta --extern openssl=/home/tide/clarinet/target/release/deps/libopenssl-2c83ca2fa6ee6e8b.rmeta --extern openssl_probe=/home/tide/clarinet/target/release/deps/libopenssl_probe-5364ebd149192269.rmeta --extern openssl_sys=/home/tide/clarinet/target/release/deps/libopenssl_sys-4f3074ab70454865.rmeta --cap-lints allow --cfg have_min_max_version`
error: aborting due to 2 previous errors

For more information about this error, try `rustc --explain E0658`.
error: could not compile `clap`

Caused by:
  process didn't exit successfully: `rustc --crate-name clap --edition=2018 /home/tide/.cargo/registry/src/github.com-1ecc6299db9ec823/clap-3.0.0-beta.4/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi --crate-type lib --emit=dep-info,metadata,link -C opt-level=3 -C embed-bitcode=no --cfg 'feature="atty"' --cfg 'feature="cargo"' --cfg 'feature="clap_derive"' --cfg 'feature="color"' --cfg 'feature="default"' --cfg 'feature="derive"' --cfg 'feature="env"' --cfg 'feature="lazy_static"' --cfg 'feature="std"' --cfg 'feature="strsim"' --cfg 'feature="suggestions"' --cfg 'feature="termcolor"' --cfg 'feature="unicode_help"' -C metadata=a3d855505ac51ae0 -C extra-filename=-a3d855505ac51ae0 --out-dir /home/tide/clarinet/target/release/deps -L dependency=/home/tide/clarinet/target/release/deps --extern atty=/home/tide/clarinet/target/release/deps/libatty-8c49f159338d06e8.rmeta --extern bitflags=/home/tide/clarinet/target/release/deps/libbitflags-b775ec35c0260123.rmeta --extern clap_derive=/home/tide/clarinet/target/release/deps/libclap_derive-f3c37e1a2ef73567.so --extern indexmap=/home/tide/clarinet/target/release/deps/libindexmap-171222540c838c94.rmeta --extern lazy_static=/home/tide/clarinet/target/release/deps/liblazy_static-0fdabdf0c41b00c5.rmeta --extern os_str_bytes=/home/tide/clarinet/target/release/deps/libos_str_bytes-a6573fe882146b4a.rmeta --extern strsim=/home/tide/clarinet/target/release/deps/libstrsim-4fb4cd4fa533a7a3.rmeta --extern termcolor=/home/tide/clarinet/target/release/deps/libtermcolor-d133e93d52de74af.rmeta --extern textwrap=/home/tide/clarinet/target/release/deps/libtextwrap-8e74302250090374.rmeta --extern vec_map=/home/tide/clarinet/target/release/deps/libvec_map-1df9fa7a81a4a8dc.rmeta --cap-lints allow` (exit code: 1)
warning: build failed, waiting for other jobs to finish...
error: failed to compile `clarinet v0.18.0 (/home/tide/clarinet)`, intermediate artifacts can be found at `/home/tide/clarinet/target`

Caused by:
  build failed`

**Comment by lgalabru** [comment]
Can you copy paste the command that you're using?
Thanks!

**Comment by Godtide** [comment]
`unzip clarinet-linux-x64.zip -d .
chmod +x ./clarinet
mv ./clarinet /usr/local/bin
`

[installation using cargo](https://github.com/hirosystems/clarinet#install-from-source-using-cargo)
