### ISSUE TITLE
Error when stopping devnet using "ctrl + c"

### ISSUE THREAD

**Issue by vicnicius** [hirosystems/clarinet#1534]
**Describe the bug**
When I stop devnet using the "ctrl + c" key combination, I see the following error:

`Error sending terminate command: sending on a disconnected channel`

All devnet containers keep running after it.

**To Reproduce**
Steps to reproduce the behaviour:
1. Start devnet `clarinet devnet start`
2. After it is running, use the `ctrl + c` combination to stop it. (I'm not familiar with any other way to stop it)
3. See error

**Expected behaviour**
I'd expect devnet tui to be stopped, as well as all related running containers.

**Environment (please complete the following information):**
 - OS (version): 14.5 (23F79)
 - Docker version: 24.0.5
 - Clarinet version: 3.28.0

**Comment by hugocaillard** [comment]
Thanks for reporting @vicnicius 
It's likely that if the devnet doesn't shutdown gracefully, it means that it's in a weird state.
Do you use `ctrl + c` immediately after starting the devnet?
Or has your devnet stopped (no more block mining) when you did `ctrl + c`

**Comment by vicnicius** [comment]
Oh, that makes sense. I think what triggered me to stop it was it stopping to produce new blocks. I'll keep an eye on it and see if I can gather any more info. Thanks! Feel free to close this issue for now, and if it happens while all services are stable, I can re-open it. If it's some service crashing without clear reason I'll make sure to open a new issue for it.

**Comment by hugocaillard** [comment]
@vicnicius 
Thanks. And to be fair, we should still be able to gracefully shutdown the devnet if it crashes, but we are also putting efforts in making sure that it doesn't.

Find on me on the official Discord (in the #clarinet chan) if you're node stops again
