### ISSUE TITLE
Missing Bitcoin Electrs Server on Devnet

### ISSUE THREAD

**Issue by DevelopOnStacks** [hirosystems/clarinet#1581]
**Describe the bug**
node sbtc package call bitcoin Electrs Api on localhost port 3002 to check utxo, but it's a missing service when deploy with clarinet devnet start

**Environment (please complete the following information):**
 - OS (version): Win11
 - Docker version 4.34.2
 - Clarinet version 2.9.0

**Comment by hugocaillard** [comment]
Hello @DevelopOnStacks 
sBTC is still a work in progress and isn't supported on Clarinet.
Can you explain the context of this, what's your use case, what your willing to do?
Thx

**Comment by DevelopOnStacks** [comment]
I tried to run lagoon example on devnet but could not do that

**Comment by hugocaillard** [comment]
@DevelopOnStacks Does the lagoon example recommand to use clarinet devnet?
Do you have a link?

**Comment by DevelopOnStacks** [comment]
Well I found it in [https://github.com/kenrogers/lagoon](https://github.com/kenrogers/lagoon) and contracts in [https://github.com/kenrogers/sbtc-starter](https://github.com/kenrogers/sbtc-starter) and assumed it could run on devnet

**Comment by hugocaillard** [comment]
So I think kenrogers/sbtc-starter should work in the devnet. I believe this is the demo here:
https://x.com/KenTheRogers/status/1821960095187771561
This is using a "mock sbtc" contract. But then I'm not sure if there a moment where you need to connect to electrs. I don't think it's requirement for sbtc anymore (it was a year ago, but that _might_ have change).

For the first link I'm not sure what the setup was but I remember it was a very manual process to get it running.

To be fair, this is a valid issue, sBTC in Clarinet doesn't work. This a more of a feature request than a bug and we are currently talking with a the sBTC team to get it working in the coming weeks

**Comment by hugocaillard** [comment]
@DevelopOnStacks 
While this is valid, I'm closing this issue in favor of https://github.com/hirosystems/clarinet/issues/1532 which tracks the needs for sbtc development in clarinet.
Feel free to subscribe to it to have the updates
