### ISSUE TITLE
Devnet - /v2/fees/transaction not found

### ISSUE THREAD

**Issue by hugocaillard** [hirosystems/clarinet#162]
When using `clarinet integrate`, the stacks-api seems to be outdated. Apparently the quay.io/hirosystems/stacks-node image hasn't been updated since 4 months.
Resulting in the endpoint `/v2/fees/transaction` to be a 404 and the wallet in unusable.

I also curled `http://localhost:20443/v2/info`:
```json
  "server_version": "stacks-node No Version Info (No Branch Info:No Commit Info, release build, linux [x86_64])",
```

Is there anything I can do to fix it? 
Please tell me if I opened this issue on the wrong repo

<img width="971" alt="Screenshot 2021-11-30 at 14 00 47" src="https://user-images.githubusercontent.com/911307/144425405-9265de93-1a46-47d5-ace5-2f073e6249e7.png">

**Comment by lgalabru** [comment]
Restarting your devnet should trigger a `stacks-node` update, feel free to close this issue if you see that it's fixed on your end.

**Comment by hugocaillard** [comment]
Hi @lgalabru, thanks a lot for the update, you rock 🙌
