### ISSUE TITLE
clarinet publish --devnet fails to deploy

### ISSUE THREAD

**Issue by pseudozach** [hirosystems/clarinet#175]
- clarinet integrate is running, all containers are deployed, I can see the explorer and transactions.
- when I try to deploy contracts to devnet I get this error after wait (times out)
- I think it is related to macos docker setup but I can't find a workaround, localhost already resolves to 127.0.0.1 on /etc/hosts

% RUST_BACKTRACE=1 clarinet publish --devnet

>thread 'main' panicked at 'Unable to retrieve account: reqwest::Error { kind: Request, url: Url { scheme: "http", cannot_be_a_base: false, username: "", password: None, host: Some(Ipv4(127.0.0.1)), port: Some(20443), path: "/v2/accounts/ST1PQHQKV0RJXZFY1DGX8MNSNYVE3VGZJSRTPGZGM", query: None, fragment: None }, source: TimedOut }', src/publish/mod.rs:87:18
stack backtrace:
   0: _rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::result::unwrap_failed
   3: clarinet::publish::publish_contract
   4: clarinet::frontend::cli::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

not sure if relevant but
`# curl http://localhost:20443/v2/info` -> returns response
`# curl http://127.0.0.1:20443/v2/info` -> no response

**Comment by lgalabru** [comment]
Thank you for raising this issue @pseudozach, will look into it.

**Comment by pseudozach** [comment]
this stopped happening after I ran `clarinet integrate` the next day. but now the same command is failing complaining about low fee rate.
it would be great to be able to customize publish fees or have it high enough so it successfully deploys them.
thanks,

**Comment by pseudozach** [comment]
`{"error":"transaction rejected","reason":"FeeTooLow","reason_data":{"actual":245,"expected":381},"txid":"24a705e5b92b2bac319ae1848b35a58d8159c89ae3b05484cd1fd3aa32066590"}`

**Comment by lgalabru** [comment]
Addressed in `v0.21.0`
