### ISSUE TITLE
Improve deployments in context of multiple contracts

### ISSUE THREAD

**Issue by lgalabru** [hirosystems/clarinet#201]
The current approach for deploying contracts has a few limitations that should be handled.
For instance, if there are more than 25 contracts in a repo, then the transaction chaining limit (25) would cause the next contracts deployments to fail.

**Comment by fariedt** [comment]
**(not a solution)**

The project I'm working with has over 80 contracts, and I didn't want to untangle the references to figure out which subset I need for my changes, so I added a sleep between deployments:
```diff
diff --git a/src/publish/mod.rs b/src/publish/mod.rs
index 5df131b..570952f 100644
--- a/src/publish/mod.rs
+++ b/src/publish/mod.rs
@@ -26,6 +26,7 @@ use libsecp256k1::{PublicKey, SecretKey};
 use std::collections::BTreeMap;
 use std::path::PathBuf;
 use tiny_hderive::bip32::ExtendedPrivKey;
+use std::{thread, time};
 
 #[derive(Deserialize, Debug)]
 struct Balance {
@@ -139,6 +140,12 @@ pub fn publish_contract(
         Err(e) => return Err(format!("{:?}", e)),
     };
     deployers_nonces.insert(deployer.name.clone(), nonce + 1);
+
+    // let wait = time::Duration::new(1, 0);
+    let wait = time::Duration::from_millis(250);
+    println!("done with {}, sleeping for 0.25 seconds", contract_name.as_str());
+    thread::sleep(wait);
+
     Ok((txid, nonce))
 }
 
```
I only work with `clarinet integrate` or a mocknet at the moment, so this band-aid is good enough for now.

**Comment by lgalabru** [comment]
Handled in a local branch, will open a PR soon.

**Comment by lgalabru** [comment]
To be addressed with https://github.com/hirosystems/clarinet/pull/240
