### ISSUE TITLE
Issue with Mempool section information

### ISSUE THREAD

**Issue by csgui** [hirosystems/clarinet#202]
When running `clarinet integrate` the Mempool section is not displaying the information accordingly. Check image below:

![image](https://user-images.githubusercontent.com/13015/148281817-8fe618c1-8450-40d8-8cd5-1d8328f540f9.png)

Details:
- run `$ clarinet integrate` in the root folder of a Clarinet project.
- Issue verified in clarinet 0.21.2.

**Comment by obycode** [comment]
Fixed in #203
