### ISSUE TITLE
Handle warnings and notes properly in LSP

### ISSUE THREAD

**Issue by obycode** [hirosystems/clarinet#206]
Currently, all diagnostics look like errors in VSCode, including the warnings and notes from the check-checker:
![image](https://user-images.githubusercontent.com/1473715/148405864-1e7241da-fee7-4de8-9ad5-b361bbc365f7.png)
We should handle each type of diagnostic correctly.

**Comment by lgalabru** [comment]
Addressed with https://github.com/hirosystems/clarinet/pull/208
