### ISSUE TITLE
To support real integration tests in clarinet cli

### ISSUE THREAD

**Issue by playerx** [hirosystems/clarinet#212]
Do you plan to support integration tests in clarinet cli tool? My goal is to run tests against testnet or devnet (clarinet integrate). As I can see now only pseudo integration tests are supported. Just to have `--networkApi` parameter and to pass the url of the stacks node api. Please share your vision and plans about it. ✌🏻

**Comment by playerx** [comment]
Btw, It's really cool that you use Deno for testing. Respect!

**Comment by lgalabru** [comment]
Hey @playerx, thank you for opening this issue. Could you unpack what you mean by: 
> As I can see now only pseudo integration tests are supported
?

Thank you!

**Comment by lgalabru** [comment]
Running integration tests in environments like Testnet or Mainnet would be pretty tedious, I personally don't think this is an approach we can / will support in Clarinet. Clarinet is focused on unit tests.
If testing your contracts on Mainnet / Testnet is a methodology that you'd like to experiment, you could just create a node project, pull stacks.js or micro stacks, submit transactions and assert results.
Just prepare yourself for a flaky test suite, you'll be constrained by bitcoin block time (10m average, but could be 1m or 45m), miner inclusion / exclusion and so on.
