### ISSUE TITLE
[Feature] Support detailed check info for multi-contracts 

### ISSUE THREAD

**Issue by tyGavinZJU** [hirosystems/clarinet#23]
Ex. I create two contracts using clarinet:
- First one is `example.clar`
- Second one is `exampleabc.clar`
- The Second contract there is a grammar fault.
And in Clarinet.toml:
```
[project]
name = "example"

[contracts.example]
path = "contracts/example.clar"
depends_on = []

[contracts.exampleabc]
path = "contracts/exampleabc.clar"
depends_on = []

[notebooks]
```

But the `clarinet check` will only show something like:
```
Closing parenthesis expected (2, 21)
Parsing error: Tried to close list which isn't open.
```

Not point to certain contract name like [contracts.exampleabc] etc.

**Comment by lgalabru** [comment]
Addressed with latest REPL, updated in https://github.com/hirosystems/clarinet/pull/11
![Screen Shot 2021-09-23 at 6 15 16 PM](https://user-images.githubusercontent.com/87777/134591418-a1015f22-0960-4149-9f7e-64403c04b659.png)
6
