### ISSUE TITLE
[Feature] Add possibility to obtain costs after each call.

### ISSUE THREAD

**Issue by LNow** [hirosystems/clarinet#24]
Right now we can get execution costs in console. It would be great if `chain.callReadOnlyFn` and `chain.mineBlock` could return such informations as well.

I've tried to implement it but failed.
It looks like first some changes needs to be made in `clarity-repl`repository - the `cost` field in the `ExecutionResult` struct is not serializable.
https://github.com/lgalabru/clarity-repl/blob/d68abbf30ad5b1f0f49d4c1f4552b08241accf7d/src/repl/mod.rs#L13-L19

Related issue in clarity-repl: https://github.com/lgalabru/clarity-repl/issues/13

**Comment by lgalabru** [comment]
Will address in https://github.com/hirosystems/clarinet/issues/41
