### ISSUE TITLE
[BUG] `clarinet contract new` overwrites content of `Clarinet.toml`

### ISSUE THREAD

**Issue by LNow** [hirosystems/clarinet#246]
When I run `clarinet contract new` it overwrites content of `Clarinet.toml` instead of adding new contract at the end of this file.
It is very, very, very annoying when we have multiple contracts organized in `Clarinet.toml` the way we want them to be organized, some comments etc. Everything is wiped and replaced with new configuration.

`clarinet contract new` should do only 3 things:
 - create new contract file
 - create new test file
 - add basic contract configuration at the end of `Clarinet.toml`

**Comment by obycode** [comment]
The fix is not as simple as I assumed, but I will still keep it high priority. Also, looking at this caused me to catch a crash in the last release, so 🙇!

**Comment by obycode** [comment]
Let's review Cargo.toml handling.

Another option is to only append to this file.

**Comment by moodmosaic** [comment]
In case it helps, here's how `git diff` looks like because of this bug:

```bash
clarinet new empty-project
cd empty-project
git init # https://github.com/hirosystems/clarinet/issues/366
git add .
clarinet contracts new hello
git diff
```

```diff
@@ -1,21 +1,25 @@
-
 [project]
 name = "empty-project"
 authors = []
+description = ""
 telemetry = false
-cache_dir = "./.requirements"
+requirements = []
+boot_contracts = ["pox", "costs-v2", "bns"]
+
+[project.cache_location]
+path = ".\\.requirements"
+[contracts.hello]
+path = "contracts/hello.clar"
 
-# [contracts.counter]
-# path = "contracts/counter.clar"
+[repl]
+costs_version = 2
+parser_version = 2
 
 [repl.analysis]
 passes = ["check_checker"]
-check_checker = { trusted_sender = false, trusted_caller = false, callee_filter = false }
 
-# Check-checker settings:
-# trusted_sender: if true, inputs are trusted after tx_sender has been checked.
-# trusted_caller: if true, inputs are trusted after contract-caller has been checked.
-# callee_filter: if true, untrusted data may be passed into a private function without a
-# warning, if it gets checked inside. This check will also propagate up to the
-# caller.
-# More informations: https://www.hiro.so/blog/new-safety-checks-in-clarinet
+[repl.analysis.check_checker]
+strict = false
+trusted_sender = false
+trusted_caller = false
+callee_filter = false
```

**Comment by lgalabru** [comment]
Duplicate https://github.com/hirosystems/clarinet/issues/417 - will close this issue.
