### ISSUE TITLE
just update to current version

### ISSUE THREAD

**Issue by LunarPunks** [hirosystems/clarinet#266]
warning: conflict between parser versions, reverting to parser v1

Can not check, test or publish contracts now.

How do i downgrade

**Comment by unclemantis** [comment]
> warning: conflict between parser versions, reverting to parser v1
> 
> Can not check, test or publish contracts now.
> 
> How do i downgrade

Saw that notice earlier.  Was not sure what to make of it. Everything is fine for me.  Roles back some changes I made to  contract while trying to abide to the new rules in check check checking or whatever i5 is called.   Hiro.  Good job! Keep at it.  Few bugs but I like where clarinet is going right now.

**Comment by LunarPunks** [comment]
None of my projects work, please advise best source to roll back

**Comment by obycode** [comment]
This warning is saying that it found some discrepancy between the new parser and the old parser, so it reverted to the old parser. Is there some other error after this?

If you can send a reproducer that gave the above warning, that would be very helpful. Thanks!

You can switch to the parser v1 with an option in your Clarinet.toml:

```toml
[repl]
parser_version = 1
```

**Comment by lgalabru** [comment]
Hey @LunarPunks! Thank you for opening this issue.
By chance, do you have some broken public repositories, or could you invite @obycode or me to one of your private repo, so we can see and investigate the issues you're facing?
Thanks!

**Comment by LunarPunks** [comment]
I have decided to just enjoy the stacks eco-system, too many issues to become a developer on stacks, maybe next year.
