### ISSUE TITLE
Error while using vscode

### ISSUE THREAD

**Issue by binovatyv** [hirosystems/clarinet#276]
Trying to create a .clar file

((impl-trait .sip009-nft-trait.sip009-nft-trait))
((define-fungible-token mynft uint))
.........
...............

clarinet check  

error: Expected whitespace or a close parens. Found: '('
warning: conflict between parser versions, reverting to parser v1
Help improve clarinet by sharing the code that triggered this warning:
https://github.com/hirosystems/clarinet/issues/new/choose

And on using clarinet console

clarity-repl v0.22.1
Enter "::help" for usage hints.
Connected to a transient in-memory database.
error: Expected whitespace or a close parens. Found: '('
warning: conflict between parser versions, reverting to parser v1
Help improve clarinet by sharing the code that triggered this warning:
https://github.com/hirosystems/clarinet/issues/new/choose

**Comment by unclemantis** [comment]
Like dood! I got that error today too, on STABLE CODE!

**Comment by LNow** [comment]
@binovatyv you get an error because your code is incorrect.

Instead of: 
```clarity
((impl-trait .sip009-nft-trait.sip009-nft-trait))
((define-fungible-token mynft uint))
```
use:
```clarity
(impl-trait .sip009-nft-trait.sip009-nft-trait)
(define-fungible-token mynft uint)
```

**Comment by binovatyv** [comment]
> @binovatyv you get an error because your code is incorrect.
> 
> Instead of:
> 
> ```clar
> ((impl-trait .sip009-nft-trait.sip009-nft-trait))
> ((define-fungible-token mynft uint))
> ```
> 
> use:
> 
> ```clar
> (impl-trait .sip009-nft-trait.sip009-nft-trait)
> (define-fungible-token mynft uint)
> ```

Thank you for checking @LNow . No, that's not an issue, I have checked different variations.

**Comment by binovatyv** [comment]
![image](https://user-images.githubusercontent.com/93253540/156083900-257ebb22-4b18-4a7f-a0e9-dd10917e1921.png)

**Comment by LNow** [comment]
Which version of Clarinet you use?
You can check that by running in console `clarinet --version`

**Comment by binovatyv** [comment]
clarinet 0.26.1


> Which version of Clarinet you use? You can check that by running in console `clarinet --version`

clarinet 0.26.1

**Comment by LNow** [comment]
Check line endings defined for this file (bottom right side of VS Code).
If it says `CRLF` like on the image, click on it and change to `LF`
![image](https://user-images.githubusercontent.com/829210/156084961-a7367505-4ec7-4700-9e15-2aba39a33a74.png)

**Comment by binovatyv** [comment]
> Check line endings defined for this file (bottom right side of VS Code). If it says `CRLF` like on the image, click on it and change to `LF` ![image](https://user-images.githubusercontent.com/829210/156084961-a7367505-4ec7-4700-9e15-2aba39a33a74.png)

Yes, it did the magic. Thank you

**Comment by LNow** [comment]
Perfect!

**Comment by binovatyv** [comment]
But the other file still have the issue, let me check line by line then

**Comment by LNow** [comment]
What if you run: `clarinet check` in console?

**Comment by binovatyv** [comment]
> What if you run: `clarinet check` in console?

mynft:3:30: error: use of unresolved variable 'uint'
(define-fungible-token mynft uint)

**Comment by LNow** [comment]
ahhh... my bad...
Try this:
`(define-fungible-token mynft u123)`
2nd argument of `define-fungible-tokne` must be type of `uint`.

**Comment by binovatyv** [comment]
> ahhh... my bad... Try this: `(define-fungible-token mynft u123)` 2nd argument of `define-fungible-tokne` must be type of `uint`.

You got it, so u123 is a type

**Comment by LNow** [comment]
It is not a type, but value.
You define token `mynft` that have total supply limited to 123 units.In fact you can change it to `u135825` `u2985328589` or any other valid `uint` value.

Please close the issue if it is resolved.

**Comment by binovatyv** [comment]
> It is not a type, but value. You define token `mynft` that have total supply limited to 123 units.In fact you can change it to `u135825` `u2985328589` or any other valid `uint` value.
> 
> Please close the issue if it is resolved.

Thank you LNow for the insight. I am checking line by line, since have the issue when I remove all the comments.

**Comment by binovatyv** [comment]
Any idea on what's wrong with this code, giving the same issue

clarinet check

error: Expected whitespace or a close parens. Found: '('
warning: conflict between parser versions, reverting to parser v1     
Help improve clarinet by sharing the code that triggered this warning:
https://github.com/hirosystems/clarinet/issues/new/choose


(define-public (mint (recipient principal))
  (let
      (
        (token-id(+ (var-get last-token-id) u1))
      )
      (asserts! (is-eq tx-sender contract-owner) err-owner-only)
      (try! (nft-mint? my-nft token-id recipient)) 
      (var-set last-token-id token-id)
      (ok token-id)
  )
)

**Comment by binovatyv** [comment]
Same one we looked earlier

**Comment by binovatyv** [comment]
Never Mind, It went away when I copied from https://book.clarity-lang.org/ch10-02-creating-a-sip009-nft.html

**Comment by binovatyv** [comment]
> @binovatyv you get an error because your code is incorrect.
> 
> Instead of:
> 
> ```clar
> ((impl-trait .sip009-nft-trait.sip009-nft-trait))
> ((define-fungible-token mynft uint))
> ```
> 
> use:
> 
> ```clar
> (impl-trait .sip009-nft-trait.sip009-nft-trait)
> (define-fungible-token mynft uint)
> ```

please note it's define-non-fungible-token
