### ISSUE TITLE
get-owner issue

### ISSUE THREAD

**Issue by binovatyv** [hirosystems/clarinet#277]
(define-read-only (get-owner (token-id uint))
  (ok (nft-get-owner? mynft token-id))
)
![image](https://user-images.githubusercontent.com/93253540/156088177-a0e669c4-3118-4a54-8a79-8f3a732f011e.png)

**Comment by unclemantis** [comment]
> (define-read-only (get-owner (token-id uint))
>   (ok (nft-get-owner? mynft token-id))
> )
> ![image](https://user-images.githubusercontent.com/93253540/156088177-a0e669c4-3118-4a54-8a79-8f3a732f011e.png)
> 

Do you have something like this toward the top of the same contract?

```
(define-non-fungible-token mynft uint)
```

**Comment by binovatyv** [comment]
issue resolved when used (define-non-fungible-token my-nft uint)

**Comment by unclemantis** [comment]
> issue resolved when used (define-non-fungible-token mynft uint)

Happy to be of assistance.  What did you have before? Just curious.

**Comment by binovatyv** [comment]
I missed non in the definition for some reason - define-fungible-token mynft uint

**Comment by unclemantis** [comment]
> I missed non in the definition for some reason - define-fungible-token mynft uint

That would do it! Take care!
