### ISSUE TITLE
using non-standard bitcoin ports lead to errors

### ISSUE THREAD

**Issue by pseudozach** [hirosystems/clarinet#278]
I've made the following changes in devnet.toml due to my environment
>bitcoin_node_p2p_port = 21444
bitcoin_node_rpc_port = 21443
bitcoin_controller_port = 21442
bitcoin_controller_block_time = 120_000

And I see the following error when I call `clarinet integrate`

![Screen Shot 2022-03-01 at 9 06 50 PM](https://user-images.githubusercontent.com/3731591/156299021-8a81f861-55c8-44cb-bde8-c98208cc5034.png)

Everything works fine, blocks are mined and both nodes are ok. Issue is just visual. 
Another side effect is, I can't scroll through the mined blocks, so it seems to cause some disruptions with the CLI GUI.

**Comment by lgalabru** [comment]
Duplicate: https://github.com/hirosystems/clarinet/issues/411
To be addressed in https://github.com/hirosystems/clarinet/pull/402
