### ISSUE TITLE
Better handling of errors in settings files

### ISSUE THREAD

**Issue by obycode** [hirosystems/clarinet#281]
If a user has a bad mnemonic in a settings file (e.g. settings/Testnet.toml), clarinet will panic instead of reporting a nice error message. Users will often see this if they have forgotten to replace the default `"<YOUR PRIVATE TESTNET MNEMONIC HERE>"`.

```
$ clarinet publish --testnet

thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: BadWordCount(5)', src/types/chain_config.rs:214:42
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by unclemantis** [comment]
I agree. Please make this happen.
