### ISSUE TITLE
clarinet test should be able to not fail on ts compile

### ISSUE THREAD

**Issue by moodmosaic** [hirosystems/clarinet#282]
If [Clarinet.test calls into Deno.test](https://blog.nikosbaxevanis.com/2022/03/05/clarity-property-based-testing-primer/#internals), then can we pass flags in `clarinet test` that will be then passed into `deno test`?

I'm particularly interested in the [`--no-check`](https://github.com/denoland/deno/issues/3321#issuecomment-695172229) flag.

So something like this is what I need:

```bash
clarinet test --no-check # internally calls `deno test --no-check`
```

I'm working on model-based testing for Clarity contracts, similar to what Echidna does for Solidity contracts, and there are some parts in my tests that are syntactically valid JavaScript, but the TypeScript part won't type-check for several reasons (e.g. `.d.ts` file missing).

If there's a way to supply a custom flag in deno then that would be great, if not I'd be happy to submit a PR for it.

**Comment by moodmosaic** [comment]
I think I got the answer for this. [It appears that an older version of deno is used](https://github.com/hirosystems/clarinet/tree/develop/vendor). In the most recents versions of it, deno [should no longer type check](https://github.com/denoland/deno/issues/3321#issuecomment-1064635765), just transpile, and so there's no need to even pass `--no-check`.

Any concerns wrt pulling the latest from deno upstream and applying [hirosystems/deno/tree/clarinet/patch-v3](https://github.com/hirosystems/deno/tree/clarinet/patch-v3) on top of it? I'd be happy to work on that, if you agree. @lgalabru @obycode

**Comment by lgalabru** [comment]
hey @moodmosaic!
glad to hear that you found a way out, thanks for looking into this. the version of deno that we are embedding is relatively recent, and the `no-check` foot gun is actually present, it is just not exposed to developers.
You'd have to add a new flag to `clarinet test` (maybe `ts-no-check` to disambiguate with clarity checks) here:
https://github.com/hirosystems/clarinet/blob/5785a6e8838cd47bf9c39a39ee7478685cf4a73f/src/frontend/cli.rs#L141

and pass it all the way down to:
https://github.com/hirosystems/clarinet/blob/5785a6e8838cd47bf9c39a39ee7478685cf4a73f/src/runnner/deno.rs#L221

@obycode and I are pretty busy with our backlog, but if you have the bandwidth and a use case for this ask, I'd be supportive :)

**Comment by lgalabru** [comment]
> I'm working on model-based testing for Clarity contracts, similar to what Echidna does for Solidity contracts

Looks fascinating! do you have a repo that we can watch / star?

**Comment by moodmosaic** [comment]
I think I'm fine for now with `// @ts-nocheck` so I'll see if a PR that adds `ts-no-check` is even needed. As for the stuff I'm on, I don't have something up yet, but if I do, I will ping you.  Thanks @lgalabru!

---

Closing for now, and if (a PR) needed I will reopen. Thanks again for the help.
