### ISSUE TITLE
[Feature] Add support for reload

### ISSUE THREAD

**Issue by moodmosaic** [hirosystems/clarinet#293]
Like, for example, ``::reload`` which would reload the Clarity contract(s) in the session.

It would work similar to what [GHCi does](https://downloads.haskell.org/~ghc/8.6.5/docs/html/users_guide/ghci.html?highlight=reload#ghci-cmd-:reload) in Haskell, though I expect other people coming from other languages with strong REPLs would appreciate this feature.

(As a workaround, one could quit `clarinet console` and re-run it, but that's overhead.)

**Comment by moodmosaic** [comment]
I think I'm happy to work on this, if I get enough time and some small guidance from you on the path forward.

**Comment by lgalabru** [comment]
Indeed, that'd be great!
This feature request was formulated here in the past https://github.com/hirosystems/clarity-repl/issues/15, so I'll close this one.
I'd be happy to help you working on this feature. Let us know if there's something we can do to help you!

**Comment by moodmosaic** [comment]
Thanks! I'd by happy to work on this. It might take me a few days to start. See you in https://github.com/hirosystems/clarity-repl/issues/15, then.
