### ISSUE TITLE
Clarinet Integrate

### ISSUE THREAD

**Issue by LunarPunks** [hirosystems/clarinet#295]
Is there a way to disable bitcoin node on local devnet (docker) and clarinet? Is bitcoin node even required for local dev tests?

Also my stacks node [booting](url) and explorer preparing remain in amber (yellow)  what can be causing this?

**Comment by lgalabru** [comment]
> Is there a way to disable bitcoin node on local devnet (docker) and clarinet? Is bitcoin node even required for local dev tests?


The goal of `clarinet integrate` is to spin up an offline setup as faithful as possible. The Stacks blockchain anchors its blocks to Bitcoin, as such Bitcoin is a required component in this setup.

> Also my stacks node [booting](https://github.com/hirosystems/clarinet/issues/url) and explorer preparing remain in amber (yellow) what can be causing this?


do you have some logs that you could share? please keep an eye on the incoming release (v0.28.0), fixing a lot issues + bringing many improvements to `clarinet integrate`.

**Comment by sabbyanandan** [comment]
Hi, @LunarPunks! Any background and the logs you can share in response to Ludo's questions ^^, that'd be helpful.

**Comment by lgalabru** [comment]
@LunarPunks feel free to re-open if you have more questions.
