### ISSUE TITLE
VSCode Extension

### ISSUE THREAD

**Issue by agraebe** [hirosystems/clarinet#31]
It would be great to offer the key functionality of Clarinet inside a VSCode extension. It could show chain details and allow to mine the next block with the click of a button. It could also show test details like existing test framework extensions.

I started rough mockups but they're not yet ready for reviews - mostly wanted to use them to see if there'd be interested (which seems to be the case)

**Comment by agraebe** [comment]
This could also allow us to merge the existing Clarity VSC extension into one "suit" of tools for Clarity development

**Comment by lgalabru** [comment]
This issue is an epic, and progress toward this goal will be tracked in the repo https://github.com/hirosystems/clarity-lsp
Closing, feel free to re-open if you had something different in mind
