### ISSUE TITLE
Sanity checks and human readable errors for Devnet

### ISSUE THREAD

**Issue by lgalabru** [hirosystems/clarinet#348]

**Comment by moodmosaic** [comment]
I just created a new VM with no docker installed, and clarinet compiled from source (`feat/dap` branch). Here's what I get:

```
$ clarinet integrate

Unable to start Devnet: make sure that Docker is installed on this machine and running.
```

That's not good enough?

**Comment by moodmosaic** [comment]
Oh, you mean to check whether docker daemon is running as a non-root user. My bad.

**Comment by koz-btc** [comment]
I'm struggling with this issue as well. I do have rootless docker install running correctly, and I'm getting the same error. Docker is there but clarinet doesn't detect this and doesn't provide any useful feedback about how to fix it.

**Comment by Oyeins-GUI** [comment]
I also have the same issues. What could fix it?

**Comment by lgalabru** [comment]
While tackling this issue, we should also make sure that all the port needed are available.

**Comment by Oyeins-GUI** [comment]
> While tackling this issue, we should also make sure that all the port needed are available.

How can we make sure that all port needed are available?

**Comment by lgalabru** [comment]
The latest versions of Clarinet are doing a better job on explaining this class of errors, closing now.
