### ISSUE TITLE
[Bug] Installing Clarinet on Windows

### ISSUE THREAD

**Issue by wallace21st** [hirosystems/clarinet#35]
Hi, I am a complete newbie to Clarity and try to see whether I can self teach myself. However, I ran into my first obstacle now when installing Clarinet on windows 10. I followed the instruction by installing Windows Visual Studio (with C++ tools and SDK) and Rust. However, I still have problem with link.exe. The error message I received is as follows. I wonder whether you might be able to help on it. Thanks,

Compiling deno_runtime v0.9.3
error: linking with `link.exe` failed: exit code: 1319

**Comment by lgalabru** [comment]
Should be addressed with latest
