### ISSUE TITLE
Update Explorer docker image to hirosystems/explorer:latest

### ISSUE THREAD

**Issue by mcintyre94** [hirosystems/clarinet#353]
The `blockstack/explorer:latest` image currently used was last updated ~6 months ago and is very buggy compared to explorer.stacks.co

The maintained Docker image is `hirosystems/explorer:latest`

That said we shouldn't do this right now because the Explorer is currently broken for all local devnet transactions (including when run in Clarinet): https://github.com/hirosystems/explorer/issues/712

But when it's in a working state, IMO it makes more sense to use that as Explorer in Clarinet since it's a lot more stable.

**Comment by lgalabru** [comment]
Addressed with latest.
