### ISSUE TITLE
Allow `clarinet console` even when Clarinet.toml is not found

### ISSUE THREAD

**Issue by obycode** [hirosystems/clarinet#355]
Many users will have `clarinet` installed, but not `clarity-repl`. There is no real reason why we should refuse to open a REPL when not inside of an existing project with a Clarinet.toml file.

**Comment by moodmosaic** [comment]
Good idea. And it should be reasonably easy to implement this, I think.

**Comment by moodmosaic** [comment]
This may require no changes in clarity-repl; perhaps all we need is
1. (L114) show a warning in the console that `Terminal` is starting with an empty/missing Clarinet.toml
2. (L117) pass empty (but valid) `settings` in `Terminal`

https://github.com/hirosystems/clarinet/blob/8ef89c504fe202d10c491f879e6f92f4da94fb99/src/poke/mod.rs#L113-L117

**Comment by obycode** [comment]
Agreed! It should be pretty straight-forward.

**Comment by moodmosaic** [comment]
Following the types lead me to something different than what I originally thought in https://github.com/hirosystems/clarinet/issues/355#issuecomment-1128627953.
