### ISSUE TITLE
Windows installer

### ISSUE THREAD

**Issue by obycode** [hirosystems/clarinet#364]
The installation of clarinet on Windows is difficult for some users. We should generate an MSI installer that would provide a very simple option for those users. This installer just needs to install the clarinet binary to some standard directory, perhaps with an option for a local (non-admin user) or a global install.

**Comment by moodmosaic** [comment]
Perhaps all we need is a [Chocolatey package](https://community.chocolatey.org/).

**Comment by moodmosaic** [comment]
It'd be nice to also distribute a clarinet.exe (executable) that can just be placed anywhere in PATH.

**Comment by obycode** [comment]
> Perhaps all we need is a [Chocolatey package](https://community.chocolatey.org/).
> 
> E.g. `$ choco install clarinet`

We do have a Winget package already, but yeah, maybe we should also add chocolatey. Issue #1 was closed at some point, but I don't think the feature is there. I will reopen that one and close this one.

**Comment by moodmosaic** [comment]
> Oops, just realized we already have a Windows installer - https://github.com/hirosystems/clarinet/releases.

Yep, just wondering if we're ever going to take advantage of the features MSI provides (IIRC, patching, admin install images, etc) since clarinet is just an exectuable and can be just placed anywhere in PATH.
