### ISSUE TITLE
Mocknet Stacks Block Time can not be set up and is different from Bitcoin Block Time

### ISSUE THREAD

**Issue by BowTiedDeployer** [hirosystems/clarinet#369]
### The bitcoin_controller_block_time setting change the time for bitcoin blocks time. There is not a direct way to set up the stacks block time. With the bitcoin block time set to 3_000 ( 3 seconds ) a stacks block happens every 3-4 bitcoin blocks ( 9 -12 seconds )

![image](https://user-images.githubusercontent.com/93231870/169866664-2ae18b91-cf49-4d6d-a959-838c3d12c486.png)

**Comment by lgalabru** [comment]
Thanks for reporting, I'll look into this.

**Comment by lgalabru** [comment]
This issue was fixed in one of the latest builds, I'll close this issue.
