### ISSUE TITLE
clarinet  test errors out after creating a new contract

### ISSUE THREAD

**Issue by amahajan87** [hirosystems/clarinet#370]
When running ‘clarinet test‘  seeing “fatal error in, line 0 unreachable code”. 

The “clarinet test” command throws this error after contract is created in the project. A blank new project doesn’t throw this error

**Image 1 - Error** 
![issue1](https://user-images.githubusercontent.com/35228483/169941287-897920b9-6594-45e3-a98c-c58824fb29a7.jpg)

**Image 2 - Clarint.toml file** 
![issue 2](https://user-images.githubusercontent.com/35228483/169941406-086ae274-6f79-490a-aa50-19e373e3d088.jpg)

**Image 3 - Contract file** 
![issue 3](https://user-images.githubusercontent.com/35228483/169941426-1b37589c-695a-4ee6-81f7-310d054e9037.jpg)

**Image 4 - Test file** 
![issue 4](https://user-images.githubusercontent.com/35228483/169941456-2e6107d7-0be3-4c69-a7f5-3dbdb3cfa149.jpg)

**Comment by jonkho** [comment]
Hi @lgalabru 
OS: macOS 12.3.1
clarinet: 0.30.0

[counter.zip](https://github.com/hirosystems/clarinet/files/8763894/counter.zip)

**Comment by obycode** [comment]
Hi @jonkho, @amahajan87. I am unable to reproduce this issue. Can you upgrade to clarinet 0.31.1 and let me know if you are still seeing this error? You'll need to update the import in counter_test.ts:

```ts
import { Clarinet, Tx, Chain, Account, types } from 'https://deno.land/x/clarinet@v0.31.0/index.ts';
```

**Comment by jonkho** [comment]
<img width="1226" alt="Screen Shot 2022-06-01 at 1 42 20 PM" src="https://user-images.githubusercontent.com/30179/171478972-2d12a99b-19a2-451b-9ffe-67eea66af658.png">

Looks like still the same error. Sounds like it's my own environment. I'm using an M1 mac.

**Comment by obycode** [comment]
It's very strange. I've also tried on an M1 Mac. The errors seem to be coming from inside V8, the underlying JS engine. Are you building clarinet or installing a binary?

**Comment by jonkho** [comment]
I downloaded the clarinet-darwin-arm64.tar.gz, unpacked it  and moved the the binary to /usr/local/bin

**Comment by obycode** [comment]
Ah, that's it! I can reproduce it with that binary. I hadn't tried that version. It looks like this binary built by our CI is using a bad V8 library or something. I will dig into it further now.

**Comment by obycode** [comment]
In the meantime, @jonkho, you can install clarinet with brew (https://brew.sh) instead, https://github.com/hirosystems/clarinet#install-on-macos-homebrew, or [build from source](https://github.com/hirosystems/clarinet#install-from-source-using-cargo) if you prefer.

**Comment by obycode** [comment]
To follow up on this, we've discovered that cross-compiling clarinet for M1 Macs will not work, due to a problem with V8, the underlying JavaScript engine used by deno. We're working on updating our release process to fix this.

**Comment by obycode** [comment]
The [asset on the release page](https://github.com/hirosystems/clarinet/releases/download/v0.31.1/clarinet-darwin-arm64.tar.gz) has now been updated with a working version as well. Thanks again for pointing out this issue @jonkho and @amahajan87!
