### ISSUE TITLE
clarinet not working in Windows 10

### ISSUE THREAD

**Issue by amahajan87** [hirosystems/clarinet#371]
OS: Windows 10

Installation command: `winget install clarinet`

The installation of version 0.30.0 is successful

Running commands on VSCode Terminal

The command to create new project `clarinet new <project-name>`, neither shoes any logs nor errors out with any logs! 

Even the command `clarinet --version` does not report anything but does not error out

**Comment by dryhumour11** [comment]
clarinet-windows-x64.msi
getting this error when installing on Windows 8 64bit

**Comment by moodmosaic** [comment]
Thank you for reporting this. It looks as [Visual C++ Redistributable Packages](https://www.microsoft.com/en-us/download/details.aspx?id=48145) isn't installed(?)

Can you share a screenshot from the list of installed software in Contron Panel?

**Comment by dryhumour11** [comment]
Here is what is installed -

[image: image.png]

**Comment by obycode** [comment]
@dryhumour11, can you try posting that image again? It didn't seem to work properly.

**Comment by lgalabru** [comment]
Closing, feel free to re-open if that issue still exits in the latest builds.
