### ISSUE TITLE
Getting-started glitches

### ISSUE THREAD

**Issue by sabbyanandan** [hirosystems/clarinet#389]
As I was going through developing contracts, I ran into a few glitches, some of which could be specific to my environment (/ ignorance). Still, I want to capture them in an issue to validate with others. Perhaps some of these can be moved to Docs repo as separate issues.

1) Abbreviate acronyms or explain them at a high level. The references to REPL, LCOV and likely others may not be understandable by many.

2) Help commands can include examples, so folks can follow them along. (example: `clarinet console [OPTIONS]` -> could be explained with an example of what `[OPTIONS]` can be)

3) VS code in-line validator stops working after replacing code fragments a few times. No more errors are shown. I switched to ["clarity.tools"](https://clarity.tools/) to get real-time feedback after ward.

4) VS code extension is unidentifiable from the marketplace. I got the following message and clicking that returned zero results.

> "You don't have an extension for debugging Clarity. Should we find a Clarity extension in the Marketplace?"

![image](https://user-images.githubusercontent.com/1562654/171034328-bdb1b9f5-4079-40c8-b175-80171cae4fd9.png)

But, I do have the plugin installed:

![image](https://user-images.githubusercontent.com/1562654/171034585-d8d3e297-f320-47bf-bf87-fbcab490ff29.png)

5) Debugging: I was unable able to step in or out or finish from within the CLI experience. I had to exit out. 

6) Debugging: Exiting from debug session requires multiple exit commands; perhaps there's an opportunity to improve.

7) Debugging: Unable to get the debug session working in VS Code. Following [README](https://github.com/hirosystems/clarinet#debug-your-contracts) instructions didn't help. 

![image](https://user-images.githubusercontent.com/1562654/171036547-3b9e6926-4a59-4110-b211-3df5f7f07de0.png)

8) Debugging: Instruction missing in the official docs.

9) Trace is advertised in [README](https://github.com/hirosystems/clarinet#execution-trace), but isn't available in 0.30.0 - is it?

10) The default formatter to format the Clarity code in VS Code makes the code hard to read. Maybe there's a Clarity-specific formatting config, which we can advertise in docs?

11) Revise the language used in the hints to make it read more formal and developer friendlier. (example: "Check out the pro tips to improve your testing process:"; pro tips?)

**Comment by lgalabru** [comment]
These are great feedbacks, thank you @sabbyanandan!

**Comment by obycode** [comment]
Looks like after the update to the LSP is published, it still doesn't show up in a search for `@category:"debuggers" clarity`... 🤔

**Comment by obycode** [comment]
It might be this:
```diff
@@ -27,7 +27,8 @@
     },
     "qna": "https://clarity-lang.org/",
     "categories": [
-        "Programming Languages"
+        "Programming Languages",
+        "Debuggers"
     ],
     "engines": {
         "vscode": "^1.43.0"
```

@hugocaillard, if you are going to be making changes to this file, can you add this change along with your other changes?

**Comment by sabbyanandan** [comment]
Update from today's pairing session with @obycode.

We will absorb 1, 2, 8, 9, and 10 as part of the larger developer resources refresh initiative in Q3. Let's ignore them here for now.

On 3, it turns out the validation is actually working. The thing that tricked me is that it only works when you "save the file", and not incrementally on every keep-up or window change. The IDE's auto-save option could address it; however, we could also always make the validation happen at the plugin level. We can create a new issue for this improvement.

4 is addressed after the release syncing.

5 and 7 works as expected. It's just my ignorance with functional flow and wrapping versus me thinking each line would be a separate code path and wishing step-in to go inside.

6 is is still unnatural DX for me; I am shell'ing inside another shell, and multiple exit inputs are odd. Not sure what we can do about it, though.

As an extension to 6, we could also automatically read and parse the contract code to auto-create the debug commands for how many ever contract are in the given file. If there's just one contract, we could automatically start the debug session with it instead of expecting the user to type `::debug (contract-call? .bookey1 increment-counter)` .. it is hard to type and/or copy+paste (not intuitive), and we want to simplify that. If there are more than 1 contract, we can list the pre-populated debug commands and request the developer select the contract they want to debug.  Maybe a new improvement issue?

In another extension to 6, we could add a top-level `clarinet debug ..` command to simplify multiple sub-commands and steps to kick start the debug sessions. Maybe a new improvement issue?

There is still something to 10. If clarity as a language doesn't have a standard formatting file, we cannot do much about it. I am used to having formatting happen on save operation in the IDE, so the default formatting in VS Code is awful for clarity.

**Comment by hugocaillard** [comment]
Closing this bucket issue.
It contains some known issue and other various tasks that a referenced in other places
