### ISSUE TITLE
Clarinet basic nft project throws error calling function on contract when using `clarinet integrate`

### ISSUE THREAD

**Issue by BowTiedDeployer** [hirosystems/clarinet#409]
the contract works on clarinet check and console
works on clarinet integrate without the calls in the end ( claim, transfer and mint)

when called clarinet integrate with (claim) in contract throws:
Microblock rthread '<unnamed>' panicked at 'Unable to decode event_data: Error("invalid type: map, expected a string", line: 0, column: 0)', src\indexer\chai

ns\stacks.rs:504:22007876
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace─ 

Project is attached in the zip bellow
[issue-contract-funciton-call-mocknet.zip](https://github.com/hirosystems/clarinet/files/8894315/issue-contract-funciton-call-mocknet.zip)

**Comment by lgalabru** [comment]
An outdated version of clarinet caused that issue, closing now.
