### ISSUE TITLE
[Feature] Generate cost analysis reports

### ISSUE THREAD

**Issue by lgalabru** [hirosystems/clarinet#41]
It would be useful to generate some sort of cost report, helping developers to get:
- Cost of each method (upper bound)
- Cost of deployments

`clarinet costs` ?

**Comment by LNow** [comment]
Yes, yes, yes!

**Comment by MarvinJanssen** [comment]
Yes, please! Maybe we want to also provide a cost explanation somewhere? (How does runtime cost relate to other costs, etc.)

**Comment by fiftyeightandeight** [comment]
This is a great idea - something we really need in place as soon as possible!

**Comment by lgalabru** [comment]
Addressed with https://github.com/hirosystems/clarinet/pull/116
