### ISSUE TITLE
New versions of containers don't work with "extended/v1/tx/"

### ISSUE THREAD

**Issue by ilyabukalov** [hirosystems/clarinet#422]
We have clarinet 0.30 continuously running since April or so.
We have UI connecting through hiro wallet (react-connect) since April as well.
And we didn't do any major changes but suddenly several days ago it stopped working.
The end point which our UI internally connects to 
```extended/v1/tx/..)```
just shows error 404
```
{
  "error": "could not find transaction by ID 0x715b84d7ac2d934ea7b20899c18103bd4a7f6b0421d82ce06b5bc4fb90be39a0"
}
```
We **don't** connect to such endpoint (extended/v1/tx/) somehow directly, it is rather internal implementation of hiro wallet extension which we connects to through our packages in UI (stacks/connect-react, stacks/blockchain-api-client).
Based on my understanding it is some mismatch between version of clarinet and client side JS packages of hiro integration.

Could you please clarify on that. Thank you.

**Comment by lgalabru** [comment]
Hi @ilyabukalov! What do you mean by "clarinet 0.30 continuously running since April or so" ?
Where and what is running exactly?
Thanks!

**Comment by ilyabukalov** [comment]
clarinet 0.30 on our VPS:
```
c51127745b81   quay.io/hirosystems/bitcoin-explorer:devnet   "docker-entrypoint.s…"   15 hours ago   Up 15 hours   3002/tcp, 0.0.0.0:8001->8001/tcp       bitcoin-explorer.koku.devnet
1bd5830d07e1   blockstack/explorer:latest                    "docker-entrypoint.s…"   15 hours ago   Up 15 hours   0.0.0.0:8000->3000/tcp                 stacks-explorer.koku.devnet
acaf13f36905   quay.io/hirosystems/stacks-node:devnet-v2     "stacks-node start -…"   15 hours ago   Up 15 hours   0.0.0.0:20443-20444->20443-20444/tcp   stacks-node.koku.devnet
092de3184d07   blockstack/stacks-blockchain-api:latest       "docker-entrypoint.s…"   15 hours ago   Up 15 hours   0.0.0.0:3999->3999/tcp                 stacks-api.koku.devnet
d1cc9dc43ee4   postgres:alpine                               "docker-entrypoint.s…"   15 hours ago   Up 15 hours   0.0.0.0:5432->5432/tcp                 postgres.koku.devnet
237c1c301bc0   quay.io/hirosystems/bitcoind:devnet-v2        "/docker-entrypoint.…"   15 hours ago   Up 15 hours   0.0.0.0:18443-18444->18443-18444/tcp   bitcoin-node.koku.devnet
```
react UI:
```
"dependencies" {
  "@stacks/blockchain-api-client": "^3.0.1",
  "@stacks/connect-react": "^13.0.0",
},
"resolutions": {
  "@stacks/transactions": "3.2.0"
}
```
They don't work with each other while couple of days ago they worked fine with the code change.
I assume it is something new recently updated in ```blockstack/stacks-blockchain-api:latest``` docker container which makes UI code incompatible.

**Comment by lgalabru** [comment]
We recently updated the docker image, from `blockstack/stacks-blockchain-api:latest` to `hirosystems/stacks-blockchain-api:latest`.
You can tune this behavior in your `settings/Devnet.toml`, and set the field `stacks_api_image_url` to the previous value (although I'd recommend updating your product, and use the latest version of the API).

Out of curiosity, are you using `Clarinet integrate` on a server for running a private shared devnet?

**Comment by ilyabukalov** [comment]
> Out of curiosity, are you using `Clarinet integrate` on a server for running a private shared devnet?

yes

**Comment by ilyabukalov** [comment]
> (although I'd recommend updating your product, and use the latest version of the API).

It does not work with either version, old or the latest. Thats why I am messaging here since it is completely unclear what is going on with containers.

**Comment by ilyabukalov** [comment]
1. could you please give us the exact version of dockers where the issue does not exist.
I have changed 
```
stacks_api_image_url = "blockstack/stacks-blockchain-api:4.0.0"
```
but it does not give an effect. The issue in UI is the same.
2. OR Could you please point on what exact changes have been made recently (week ago or so)
3. OR Could you please elaborate more what is supposed versions we should use in our UI (at your best knowledge):
```"dependencies" {
  "@stacks/blockchain-api-client": "^3.0.1",
  "@stacks/connect-react": "^13.0.0",
},
"resolutions": {
  "@stacks/transactions": "3.2.0"
}
```
4. Could you please shed light on the return value of the end point on the current deployment.
```extended/v1/tx/..)```
```
{
  "error": "could not find transaction by ID 0x715b84d7ac2d934ea7b20899c18103bd4a7f6b0421d82ce06b5bc4fb90be39a0"
}
```
Since it is irrelevant to our UI software, it can be reproduced right in browser as for now while before it was not noticed.

What I can 100% assure is that our existing unchanged codebase were working a week ago while now it does not. Which means the issue is outside of our codebase (supposedly in containers). If we were able to revert clarinet containers to the exact the same versions which was several weeks ago - this would be the perfect solution!

**Comment by ilyabukalov** [comment]
I apologize for for disturbing previously. The issue is resolved and was caused by inconsistency of our internal development flow.
And thank you so much to let us know how to freeze dockers version in clarinet. It was very helpful. :)
