### ISSUE TITLE
Revisit deno vendoring

### ISSUE THREAD

**Issue by lgalabru** [hirosystems/clarinet#423]
It looks like the deno team started unbundling their stack. We should explore what is possible with these 2 repos:
- https://github.com/denoland/deno_emit
- https://github.com/denoland/deno_graph

Thanks to this effort, we might be able to get rid of our vendored fork of deno - which would be way healthier.
Would resolve https://github.com/hirosystems/clarinet/issues/393

**Comment by lgalabru** [comment]
Undocumented, unfortunately, but happy to hop on a call if you'd like to have an overview.

**Comment by moodmosaic** [comment]
Yep, [let's document some of this](https://calendly.com/moodmosaic/30min) so that it's available for anyone else that might want to dive in.

**Comment by moodmosaic** [comment]
🏓

**Comment by hstove** [comment]
I understand that un-vendoring would be a pain, but what about upgrading the base version of `Deno`? For example, I'd like to write [BDD-style tests](https://deno.land/manual/testing/behavior_driven_development#behavior-driven-development), but the version of Deno that Clarinet runs doesn't have support for `Deno.TestContext`.

**Comment by moodmosaic** [comment]
If you're interested in the BDD-style hooks mentioned on that Deno link, perhaps you'll find the work from @LNow and myself in [this](https://github.com/LNow/testing-example) repo interesting.

**Comment by lgalabru** [comment]
To be addressed in https://github.com/hirosystems/clarinet/pull/511.
