### ISSUE TITLE
clarinet check fail with 'unable to retrieve contract' error

### ISSUE THREAD

**Issue by pradel** [hirosystems/clarinet#431]
When adding arkadiko SP2C2YFP12AJZB4MABJBAJ55XECVS7E4PMMZ89YZR.arkadiko-swap-v2-1 smart contract as a requirement, `clarinet check` throw an 'unable to retrieve contract' error.

```
RUST_BACKTRACE=full clarinet check
thread 'main' panicked at 'unable to retrieve contract', src/frontend/cli.rs:1438:18
stack backtrace:
   0:        0x104d3b9d0 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h1fcf5822ec0595d6
   1:        0x104d558dc - core::fmt::write::hd4312e875444daaf
   2:        0x104d254d8 - std::io::Write::write_fmt::h6fe61d5a2c45611b
   3:        0x104d2a9cc - std::panicking::default_hook::{{closure}}::h33762d2c242ef766
   4:        0x104d2a690 - std::panicking::default_hook::h6d8535317e31e739
   5:        0x104d2aee8 - std::panicking::rust_panic_with_hook::hbed5b5f05ae7b6c2
   6:        0x104d3bcd8 - std::panicking::begin_panic_handler::{{closure}}::he6e992d2f2d44613
   7:        0x104d3bae4 - std::sys_common::backtrace::__rust_end_short_backtrace::h163559e3b58ec18c
   8:        0x104d2aae0 - _rust_begin_unwind
   9:        0x104dfac2c - core::panicking::panic_fmt::h20603f0cb36d804e
  10:        0x104d5c540 - core::panicking::panic_display::h0278292e9fbdbccf
  11:        0x104d5c504 - core::panicking::panic_str::h05dbb530ef91ee4d
  12:        0x104dfad28 - core::option::expect_failed::h20a45c18a5a61a8d
  13:        0x102a9d3f8 - clarinet::frontend::cli::DiagnosticsDigest::new::h03eb389e85e61bfc
  14:        0x102a94a88 - clarinet::frontend::cli::main::h080379bb735b271d
  15:        0x1027904ec - std::sys_common::backtrace::__rust_begin_short_backtrace::h931321b196b83098
  16:        0x102b00b7c - std::rt::lang_start::{{closure}}::h5bfa2267760a1d99
  17:        0x104d1fcd8 - std::rt::lang_start_internal::h933a358395d5a923
  18:        0x10277b210 - _main
```

I created a repository reproducing the issue https://github.com/pradel/clarinet-issue-431.
The repository is showing the issue with a contract created by arkadiko https://explorer.stacks.co/txid/SP2C2YFP12AJZB4MABJBAJ55XECVS7E4PMMZ89YZR.arkadiko-multi-hop-swap-v1-1?chain=mainnet.

What I did:
1. run `clarinet new xxx`
2. edit the counter.clar by adding the contract code to it
3. run `clarinet requirements add SP2C2YFP12AJZB4MABJBAJ55XECVS7E4PMMZ89YZR.arkadiko-swap-v2-1`
4. run `clarinet check` and get the error

Note: adding requirements for other contracts worked fine, it's only with this specific one that I am having the issue.
I am using clarinet 0.32.0.

**Comment by obycode** [comment]
This looks like an issue with the default deployment plan used when no file is specified. If I generate the default deployment plan first, with `clarinet deployments generate`, then run `clarinet check`, it works as expected.

**Comment by obycode** [comment]
Clarinet seems to be failing to include the contract in the `deployment.contracts` because it has warnings. If I disable the check-checker, there are no warnings in that contract, and then the check is successful.

**Comment by pradel** [comment]
@obycode just tried to run `clarinet deployments generate` and it fixed the issue for me, now I can run `clarinet check` without error

**Comment by obycode** [comment]
Okay, great. That should be a good workaround until the bug is fixed.

**Comment by lgalabru** [comment]
To be fixed in https://github.com/hirosystems/clarinet/issues/431, I ended up running into this issue while working on this PR.
