### ISSUE TITLE
Where should new clarity-repl PRs go?

### ISSUE THREAD

**Issue by moodmosaic** [hirosystems/clarinet#437]
Inside this repo, in [components/clarity-repl](https://github.com/hirosystems/clarinet/commit/2bf434fad806c19e5e1aa224d04125617ea6b34c) directory, or [https://github.com/hirosystems/clarity-repl](https://github.com/hirosystems/clarinet/issues/new)?

@lgalabru

**Comment by lgalabru** [comment]
In this repo 👍
I've just archived `clarity-reply` to make it more clear.

**Comment by moodmosaic** [comment]
Yep, monorepos sometimes work great, and in this case it makes sense. Perhaps it could have been added as a git submodule(?)
