### ISSUE TITLE
Parser raising placeholder related issue

### ISSUE THREAD

**Issue by lgalabru** [hirosystems/clarinet#447]
```clarity
;; counter
;; let's get started with smart contracts
(define-data-var counter uint u1)

&

(define-constant CONTRACT_OWNER tx-sender)
```
raise 2 errors:
```bash
error: unknown symbol, '&'
--> contracts/counter.clar:7:1
&
^
error: unexpected 'placeholder'
--> contracts/counter.clar:7:1
&
^
```

**Comment by obycode** [comment]
The new parser about to be merged into the blockchain (stacks-network/stacks-blockchain#3150) replaces these "placeholders" with a new placeholder node that should be handled more cleanly. I will revisit this after merging the canonical VM back into the REPL (#474).
