### ISSUE TITLE
Bad error if `use-trait` is the only expression in a contract

### ISSUE THREAD

**Issue by obycode** [hirosystems/clarinet#460]
If a contract is defined like this:

```
(use-trait some-trait .foo.some-trait)
```

Obviously, this is not a useful contract, but it should not be illegal.The repl will panic with something like:

```
thread 'analysis::dependency_detector::tests::use_trait' panicked at 'called `Result::unwrap()` on an `Err` value: Unchecked(UndefinedFunction("use-trait"))', src/repl/interpreter.rs:456:89
```

The code causing this is checking if there is only one expression and it does not contain `(define-`, then it attempts to evaluate the expression, which is correct, except for `use-trait` and `impl-trait` which should be handled similarly to the `define-*` expressions.

**Comment by lgalabru** [comment]
Tested and fixed in latest version.
