### ISSUE TITLE
Support Clarity language changes in Stacks 2.1

### ISSUE THREAD

**Issue by obycode** [hirosystems/clarinet#465]
<s>With the switch to 2.1, we have the opportunity to make some breaking changes to the language. It would make sense to put together a formal specification of the language, including some breaking changes (e.g. limitations on symbol names like `this<is>con/fus!ing*`). It would be nice to have a BNF specification (or something else). The new parser (see hirosystems/clarity-repl#74) will implement these changes.</s>

The task to define the language specification has been moved to https://github.com/stacks-network/stacks-blockchain/issues/3052. This issue should track that issue and make the corresponding changes in the REPL parser.

**Comment by lgalabru** [comment]
@obycode now that everything lives on the stacks-blockchain side, can we close this issue?
