### ISSUE TITLE
Arithmetic underflow crashes clarity-repl instead of displaying error

### ISSUE THREAD

**Issue by criadoperez** [hirosystems/clarinet#471]
If you try to subtract two unsigned values clarity-repl panics and crashes. Example of (- u5 u7) below.
Shouldn't a more correct behavior be to report the "Arithmetic Underflow" like it reports other errors, but without crashing the application?

`
clarity-repl v0.16.0
Enter "::help" for usage hints.
Connected to a transient in-memory database.
>> (- 5 u7)
Analysis error: expecting expression of type 'int', found 'uint'
(- 5 u7)
>> (- u5 7)
Analysis error: expecting expression of type 'uint', found 'int'
(- u5 7)
>> (- u5 u7)
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Runtime(ArithmeticUnderflow, Some([]))', src/repl/interpreter.rs:215:89
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
`

**Comment by lgalabru** [comment]
Addressed with https://github.com/hirosystems/clarinet/pull/535
