### ISSUE TITLE
Feat: have ability to load MARF state

### ISSUE THREAD

**Issue by 617a7a** [hirosystems/clarinet#473]
For Halo, we want to cache the current MARF state globally and move the execution of read-only calls to the client, so they become much more scalable, faster and more private.

I'm guessing for this we'll need to be able to load a contract's "state" into the REPL, as well as have bridges for some functions (eg, get stx balance of an address).

Still looking into how to do this, so it might be better to open a discussion?

**Comment by hugocaillard** [comment]
Sorry for asking again more than a year later, is this still relevant @617a7a?

**Comment by smcclellan** [comment]
Hey @617a7a, please follow up on Discord if this is still needed. I'll close this for now due to inactivity.
