### ISSUE TITLE
Revise and update ReadMe for a better Onboarding experience 

### ISSUE THREAD

**Issue by saralab** [hirosystems/clarinet#478]
- Review current ReadMe and identify improvements and updates for a better "Getting Started" experience. 
- Update FAQ : https://drive.google.com/drive/folders/1QjWJJoE4lNMiK8TJ5CtdmwYaxpj5KecV for most often asked questions and issues

**Comment by moodmosaic** [comment]
This is a great idea. 👍 Perhaps a README (re)structure like this can help: 

1. Organization ([example](https://github.com/ma-shamshiri/Human-Activity-Recognition#-book-table-of-contents))
2. Aim/Purpose ([example](https://github.com/aimeos/aimeos-typo3#readme))
3. Visuals ([example](https://github.com/anfederico/Clairvoyant#readme))
4. Instructions ([example](https://github.com/alichtman/shallow-backup#readme))

(From my [notes](https://github.com/moodmosaic/bookmarks/commit/07b3d08ce42129409a1e9b2f913a434bcecc18a2#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R1789-R1790), with all credits going to @mroker242.)

**Comment by sabbyanandan** [comment]
@LakshmiLavanyaKasturi: Could we verify if this is already taken into account with docs.hiro.so nav-flow redo?
