### ISSUE TITLE
unable to create a new project 

### ISSUE THREAD

**Issue by jingstat** [hirosystems/clarinet#48]
Installed clarinet from git source using Cargo.  Get the following error message when trying to create a new project using clarinet new my-project.  Any help?    
"""
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "The system cannot find the file specified." }', src\frontend\cli.rs:414:48
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
"""

**Comment by agraebe** [comment]
I'm seeing the same error

```
$ clarinet new billboard-clarity && cd billboard-clarity
Creating directory billboard-clarity
Creating directory billboard-clarity/contracts
Creating directory billboard-clarity/settings
Creating directory billboard-clarity/tests
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }', src/frontend/cli.rs:414:48
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

This showed up after I installed from sources using cargo

**Comment by lgalabru** [comment]
Addressed with latest master (not published on crates.io, git pull required).
