### ISSUE TITLE
`clarinet version` should return correct version

### ISSUE THREAD

**Issue by whoabuddy** [hirosystems/clarinet#50]
When I run `cargo install clarinet --locked`, it shows that package `clarinet v0.10.0` is installed

When I run `clarinet version`, it returns `clarinet 1.0`.

Should these match?

**Comment by lgalabru** [comment]
Addressed with latest master (not published on crates.io, git pull required).

**Comment by whoabuddy** [comment]
Confirmed this is working - thank you!

**Comment by Shahzayb** [comment]
I'm getting this error:
 ```Updating crates.io index
error: could not find `clarinet` in registry `https://github.com/rust-lang/crates.io-index` with version `*`
```
when running the `cargo install clarinet --locked` command.
