### ISSUE TITLE
Keep generated Deno lib in sync automatically

### ISSUE THREAD

**Issue by obycode** [hirosystems/clarinet#507]
When a new version is released, there is nothing currently in place to automate the code generated in https://github.com/hirosystems/clarinet/blob/3a1ba93fa2fff4f9a0ee213edf493163ccbfdc65/components/clarinet-cli/src/generate/contract.rs#L79

We should be able to add something in the release script to do this for us, reading from an environment variable or something.

**Comment by lgalabru** [comment]
To be addressed in https://github.com/hirosystems/clarinet/pull/511
