### ISSUE TITLE
500 Internal Server Error for deno.land

### ISSUE THREAD

**Issue by pseudozach** [hirosystems/clarinet#516]
This is probably more of a deno.land issue but I intermittently get 500 error when trying to run `clarinet test`.

It goes away after a few tries. Is there a workaround/alternative to avoid this?

>clarinet test tests/nft-bridge_test.ts
Import 'https://deno.land/x/clarinet@v0.31.0/index.ts' failed: 500 Internal Server Error
    at file:///Users/z/Documents/bridge-clarity/tests/nft-bridge_test.ts:2:0

**Comment by lgalabru** [comment]
hey @pseudozach! thank you for opening this issue. unfortunately, beside maintaining a mirror dedicated to beat deno.land's uptime (which sounds ambitious and a full time job), there's not much we can do :)
