### ISSUE TITLE
Support target x86_64-unknown-linux-musl

### ISSUE THREAD

**Issue by lgalabru** [hirosystems/clarinet#518]
See https://github.com/stacks-network/stacks-blockchain/pull/3243#discussion_r948293051

**Comment by jcnelson** [comment]
I'm not sure how tractable this is to fix, because it happens in the `deno` dependency.  Here are the relevant parts of `cargo build`:

```
$ cargo build
<snip>
error: failed to add native library /home/jude/pkg/clarinet/target/debug/gn_out/obj/librusty_v8.a: file too small to be an archive

error: could not compile `rusty_v8` due to previous error
warning: build failed, waiting for other jobs to finish...
error: build failed
```

I traced this to this issue [here](https://github.com/denoland/rusty_v8/issues/49), which has been open since Dec 2019.

**Comment by lgalabru** [comment]
Related https://github.com/hirosystems/clarinet/issues/560

**Comment by hugocaillard** [comment]
Deno (and especially our outdated version) brings many compilation issues.
To be re-assessed once we remove Deno as part of https://github.com/hirosystems/clarinet/pull/1157

**Comment by lgalabru** [comment]
Clarinet 2 is out, closing now!
