### ISSUE TITLE
[BUG] Typescript imports doesn't match latest release.

### ISSUE THREAD

**Issue by LNow** [hirosystems/clarinet#52]
Imports used in examples and in test files generated when we call `clarinet contract new <contract_name>` doesn't match with latest release tag.

They all points to `v0.13.0` 
https://github.com/hirosystems/clarinet/blob/9be1f72fd47d35d86209d797116c611d74ba33dc/examples/counter/tests/counter_test.ts#L1
while latest release has been tagged with date `2021-06-23`

Incorrect: https://deno.land/x/clarinet@v0.13.0/index.ts
Correct: https://deno.land/x/clarinet@2021-06-23/index.ts

**Comment by lgalabru** [comment]
v0.13.0 published on deno.land, thank you @LNow!
