### ISSUE TITLE
Installation of clarinet-cli v0.33.0 from source with cargo on Ubuntu

### ISSUE THREAD

**Issue by Oyeins-GUI** [hirosystems/clarinet#522]
I got this `error:` failed to compile clarinet-cli v0.33.0 (/home/oyeins/clarinet/component/clarinet-cli), intermediate artifacts can be found at /home/oyeins/clarinet/target Caused by: could not compile 'clarinet-cli'`

**Comment by obycode** [comment]
Adding from Discord: using cargo 1.59.0.

Is this on x86 @Oyeins-GUI?

**Comment by Oyeins-GUI** [comment]
> Adding from Discord: using cargo 1.59.0.
> 
> Is this on x86 @Oyeins-GUI?

It's x64

**Comment by obycode** [comment]
Please upgrade rust. I can reproduce a problem when using 1.59.0 but it works at 1.62.0.
