### ISSUE TITLE
Possible cost calculation issue

### ISSUE THREAD

**Issue by whoabuddy** [hirosystems/clarinet#524]
We deploy a "tardis" contract that uses `at-block` to pull historical information from CityCoins contracts. It's a very basic contract and used in conjunction with a vote contract as seen here:

- [Tardis V2 on Explorer](https://explorer.stacks.co/txid/SP2NS7CNBBN3S9J6M4JJHT7WNBETRSBZ9KPVRENBJ.citycoin-tardis-v2?chain=mainnet) / [GitHub](https://github.com/citycoins/contracts/blob/develop/contracts/tardis/mainnet/citycoin-tardis-v2.clar)
- [Vote V1 on Explorer](https://explorer.stacks.co/txid/SP34FHX44NK9KZ8KJC08WR2NHP8NEGFTTT7MTH7XD.citycoins-vote-v1?chain=mainnet) / [GitHub](https://github.com/citycoins/contracts/blob/develop/contracts/vote/mainnet/citycoins-vote-v1.clar)

For an upcoming vote, we've [deployed a new tardis](https://explorer.stacks.co/txid/SP2NS7CNBBN3S9J6M4JJHT7WNBETRSBZ9KPVRENBJ.citycoin-tardis-v3?chain=mainnet) / [GitHub](https://github.com/citycoins/contracts/blob/feat/stabilize-vote/contracts/tardis/mainnet/citycoin-tardis-v3.clar) and it is failing because it exceeds the read length (107905 / 100000):

```
Unchecked(CostBalanceExceeded(ExecutionCost { write_length: 0, write_count: 0, read_length: 107905, read_count: 17, runtime: 125602 }, ExecutionCost { write_length: 0, write_count: 0, read_length: 100000, read_count: 30, runtime: 1000000000 }))
```

When testing [a similar, local version](https://github.com/citycoins/contracts/blob/feat/stabilize-vote/contracts/tardis/local/citycoin-tardis-v3.clar) of the contract, the output of `clarinet test --costs` shows this value as *much* lower:

```
├──────────────────────────────────────────┼──────────┼──────────────────────────┼──────────────────────┼─────────────────────────┼─────────────────────┼──────────────────────┼──────────────┤
│                                          │ # Calls  │ Runtime (units)          │ Read Count           │ Read Length (bytes)     │ Write Count         │ Write Length (bytes) │ Tx per Block │
├──────────────────────────────────────────┼──────────┼──────────────────────────┼──────────────────────┼─────────────────────────┼─────────────────────┼──────────────────────┼──────────────┤
│ get-stacker-stats                        │        3 │  min:  114042  (0.002%)  │  min:  18  (0.120%)  │  min:  91411  (0.091%)  │  min:  0  (0.000%)  │   min:  0  (0.000%)  │          833 │
│                                          │          │  max:  114042  (0.002%)  │  max:  18  (0.120%)  │  max:  91411  (0.091%)  │  max:  0  (0.000%)  │   max:  0  (0.000%)  │          833 │
│                                          │          │  avg:  114042  (0.002%)  │  avg:  18  (0.120%)  │  avg:  91411  (0.091%)  │  avg:  0  (0.000%)  │   avg:  0  (0.000%)  │          833 │
├──────────────────────────────────────────┼──────────┼──────────────────────────┼──────────────────────┼─────────────────────────┼─────────────────────┼──────────────────────┼──────────────┤
```

The core contract that the tardis contract queries for information did increase slightly in size, and I think I have a workaround, but it would've been nice if the cost testing showed this could be a potential issue.

See citycoins/contracts#208 for more detail.

**Comment by lgalabru** [comment]
Should be addressed with the latest VM integration
