### ISSUE TITLE
Look into `clarinet` CPU usage during `clarinet integrate`

### ISSUE THREAD

**Issue by obycode** [hirosystems/clarinet#545]
robert.dlc in the Discord server [noticed](https://discord.com/channels/621759717756370964/839633619261456444/1024313635083927693):
> What exactly is clarinet as a process doing during an integrate, to use 99% CPU power? Isn't the mining process run in the stacks-node?
Either way, is there a best practice to minimize it's footprint? I would think running a fixed blocktime mocknet should not use up a ton of resources. Thanks!

I verified the same behavior on my M1 Mac. This seems worth looking into and improving.

**Comment by c0d3rk1d** [comment]
Echoing from discord.. screenshot of CPU profiler on my laptop Intel MacPro 12.6

https://discord.com/channels/621759717756370964/839633619261456444/1024358212511731775

<img width="1552" alt="Screen Shot 2022-09-27 at 12 25 20 PM" src="https://user-images.githubusercontent.com/43936814/192585519-95ccfb15-2ee6-4ac8-8389-729d9dd7e8b7.png">
<img width="984" alt="Screen Shot 2022-09-27 at 12 32 33 PM" src="https://user-images.githubusercontent.com/43936814/192585537-01b34163-1f46-4db2-b719-6df400d3a3ed.png">

**Comment by lgalabru** [comment]
To be addressed in https://github.com/hirosystems/clarinet/pull/565
