### ISSUE TITLE
First mineEmptyBlockUntil does not mine to correct block height

### ISSUE THREAD

**Issue by whoabuddy** [hirosystems/clarinet#546]
I noticed this while testing something for CityCoins, in which we wanted to fast forward to the activation block 24,497, do some mining, then fast-forward to an upgrade height in the future.

In a few spots of the code we're using `mineEmptyBlockUntil()` to progress the chain, but the results on the first call are off.

Here's a snippet as an example with our workaround:

```ts
console.info(chain.mineEmptyBlockUntil(100));
console.info(chain.mineEmptyBlockUntil(24497)); // MIA activation height
const block = chain.mineBlock([
  coreV2.testInitializeCore(coreV2.address),
  coreV2.testSetActivationThreshold(1),
  coreV2.registerUser(wallet),
]);
const activationBlockHeight =
  block.height + MiamiCoinCoreModelV2.ACTIVATION_DELAY;
console.info(activationBlockHeight);
console.info(chain.mineEmptyBlockUntil(activationBlockHeight));
```

- the first console.info returns 102 instead of 100
- the second returns 24497 as expected
- the third and fourth return 24500 as expected
- all additional calls to that function seems to be working correctly too

I'm currently using `clarinet-cli 0.33.0`.

**Comment by lgalabru** [comment]
Depending on the number of contracts you have in your protocol, the `chain` ends up being "ready" at a different height.
Deployment plans are emulating transaction chaining, so batch of 25 contracts, submitted and mined.
If you 26 contracts, you'll end up with 2 batches, meaning 2 blocks will be mined when the chain starts.
You can manually tweak your simnet deployment plans by merging all the contracts in one batch.

**Comment by lgalabru** [comment]
Closing, feel free to re-open if you think we should revisit that spec.

**Comment by whoabuddy** [comment]
No that makes sense, I haven't tried modifying the deployment plan yet but will keep that in mind. Can use the workaround for now.
