### ISSUE TITLE
Allow clarinet to access functions that are private (to enable unit testing)

### ISSUE THREAD

**Issue by a3slade** [hirosystems/clarinet#547]
It would be helpful if clarinet allowed private functions to be called directly for purposes of unit testing without marking them as public.

**Comment by cylewitruk** [comment]
+1 on this.  Are there any "best practice" strategies for how to ensure proper testing of private functions today?

**Comment by obycode** [comment]
How about a way to append clarity code to a contract in the unit test framework, so that code could contain the wrapper public functions needed to test your private functions? That would enable the unit-testing of private functions without needing to pollute the contract or modify the VM at all.
