### ISSUE TITLE
Readme: Update Clarinet.toml configuration

### ISSUE THREAD

**Issue by LakshmiLavanyaKasturi** [hirosystems/clarinet#549]
Current configuration in Clarinet.toml:

[project.cache_location]
path = ".cache"
[contracts.bbtc]
path = "contracts/bbtc.clar"

Update it to:

[contracts.my-contract]
path = "contracts/my-contract.clar"

**Comment by lgalabru** [comment]
@LakshmiLavanyaKasturi Feel free to re-open this issue if you think we still need to address this issue.
