### ISSUE TITLE
Cannot make http request from within clarinet test

### ISSUE THREAD

**Issue by lazerbeam-dev** [hirosystems/clarinet#566]
// deno says it requires flag "--allow-net" to make http request but do not know a way to set this flag from clarinet

// code below

// @ts-ignore
import { Clarinet, Tx, Chain, Account, types } from 'https://deno.land/x/clarinet@v0.31.0/index.ts';
// @ts-ignore
import { assertEquals } from 'https://deno.land/std@0.90.0/testing/asserts.ts';
// @ts-ignore
import axiod from "https://deno.land/x/axiod/mod.ts";

Clarinet.test({
    name: "Ensure that we can get a price from Redstone",
    async fn(chain: Chain, accounts: Map<string, Account>) {
        axiod.get("https://api.redstone.finance/prices?symbol=STX&provider=redstone&limit=1")
            .then(function (response) {
              console.log(response.data)
            });
    },
});

**Comment by lgalabru** [comment]
I can confirm that 
```bash
$ clarinet test
```
with
```js
// @ts-ignore
import { assertEquals } from "https://deno.land/std@0.90.0/testing/asserts.ts";
// @ts-ignore
import axiod from "https://deno.land/x/axiod/mod.ts";

Clarinet.test({
  name: "Ensure that we can get a price from Redstone",
  async fn(chain: Chain, accounts: Map<string, Account>) {
    let response = await axiod.get(
      "https://api.redstone.finance/prices?symbol=STX&provider=redstone&limit=1",
    );
    console.log(response.data);
  },
});
```
works as expected with the develop branch.
