### ISSUE TITLE
DAP: v1.0 silently fails when called from the VS Code extension

### ISSUE THREAD

**Issue by hugocaillard** [hirosystems/clarinet#580]
When the VS Code extension tries to invoke the DAP, it silently fails.
It still works with  clarinet v0.33.0

**Comment by hugocaillard** [comment]
Maybe related to #435 
But with an error happening only since clarinet v1.0

**Comment by obycode** [comment]
I found the problem. The hooks don't get propagated in `eval` anymore.

https://github.com/hirosystems/clarinet/commit/38219d028281a03f4b8214ddfc6cae3928183618#diff-2679a68a745fbd11e6ec23ee739205d53557691d54138cea08dd7266448815b5L879

I'll add them back and test.
