### ISSUE TITLE
Missing chainhook dependencies

### ISSUE THREAD

**Issue by whoabuddy** [hirosystems/clarinet#581]
I was walking through [the example here](https://github.com/hirosystems/clarinet/tree/develop/components/clarinet-cli/examples/cbtc) and had to tweak a few things to get it working. I also wanted to verify the experience as I haven't used `clarinet integrate` much.

From the `develop` branch at the path:
`/clarinet/components/clarinet-cli/examples/cbtc`

Ran `clarinet integrate` and didn't have Docker installed - the first time there was no error but the screen was cleared out and I was back at my prompt. From there I assumed it was running, but in trying again see this message:

`unable to start Devnet: make sure that Docker is installed on this machine and running.`

Then from the `serverless` folder underneath that, ran into an issue with plugins.

```
yarn global add serverless <-- works
serverless offline --verbose --printOutput <-- fails
```

That second command fails due to a missing package for `serverless-plugin-typescript` - now I see that's in the package.json for the serverless folder and didn't catch that before, so it would likely be resolved with just running `yarn` first.

What was interesting, though, is that the error from running the serverless command recommends running this:

`serverless plugin install -n serverless-plugin-typescript`

That didn't work for me, it invoked `npm` instead of `yarn` and failed to find the correct place to install it.

From the serverless directory I was able to run `yarn add --dev serverless-plugin-typescript@latest` and now the `serverless offline` command works as expected.

Operating system: Linux Mint 20.3 Cinnamon (based on Ubuntu 20.04.5 LTS Focal Fossa)

**Comment by lgalabru** [comment]
Thanks @whoabuddy! I'll address your feedbacks #583.

**Comment by lgalabru** [comment]
Documentation enhanced with `v1.0.4`
