### ISSUE TITLE
enable allow-read option during test

### ISSUE THREAD

**Issue by pseudozach** [hirosystems/clarinet#587]
I'd like to be able to deploy a contract at a certain point in a clarinet test. 

I can manually put contract code into a string and then call `Tx.deployContract` to deploy a contract, but ideally I'd like to be able to pull this from a file. When I try to use Deno.readTextFile I get below error:

> Uncaught (in promise) PermissionDenied: Requires read access to "contracts/xxx.clar", run again with the --allow-read flag
const contractCode = await Deno.readTextFile("contracts/xxx.clar");

I'm also having trouble getting clarinet to avoid the file under contracts/xxx.clar, even if I remove it from `Clarinet.toml` it still seems to deploy it when I launch clarinet console.

**Comment by lgalabru** [comment]
Thanks for surfacing this issue @pseudozach! We never had a feature request for `allow read`, but most of the plumbing is there so we should be able to include that in the next releases.

> I'm also having trouble getting clarinet to avoid the file under contracts/xxx.clar, even if I remove it from Clarinet.toml it still seems to deploy it when I launch clarinet console.

Strange, do you have a repo that you can share? Thanks!

**Comment by vicnicius** [comment]
Hey there! I've also faced the same issue while trying to implement a similar use case. For me specifically, I'd also like to enable allow-env.
