### ISSUE TITLE
`clarinet run` no longer supports `import.meta.main`

### ISSUE THREAD

**Issue by hstove** [hirosystems/clarinet#589]
This is a small issue, and it has an easy workaround. I'm mainly noting it in case anyone runs into this.

Before Clarinet v1, when using `clarinet run`, you could utilize Deno's `import.meta.main` pattern to only run certain code if you were running that script directly. Now, `import.meta.main` returns false.

As an example, have a file `script.ts` and run `clarinet run script.ts`.

Before v1, this worked:

```ts
if (import.meta.main) { console.log('hello') }
```

After v1, "hello" is not printed (`main` is false).

The workaround is simple:

```ts
console.log('hello'); // no `import.meta.main` usage
```

As a side note, `clarinet run` now prints out test results, as if I was running `clarinet test`. For a basic script, there are no tests. I'd imagine these two are somehow related, and of course related to the recent internal Deno refactoring.

Again - this is not a big issue. If it requires any non-trivial work to fix, I'd say it shouldn't be a priority, and you should feel free to close this issue. Thanks!

**Comment by smcclellan** [comment]
Thank you for filing this! I'm closing it for now as we are moving away from deno in clarinet 2.0 and I expect this not to be an issue for long.

**Comment by hstove** [comment]
> we are moving away from deno in clarinet 2.0

woah, interesting! is there somewhere i can learn more about the vision for 2.0?
