### ISSUE TITLE
[Feature] Cache initial chain state between tests

### ISSUE THREAD

**Issue by LNow** [hirosystems/clarinet#59]
Every single test causes full chain reset. There is nothing wrong with it, but it takes time to:
- create new session
- load bns and sip010 contracts
- load toml configuration
- prepare accounts
- parse user contracts
- load user contracts
- move chain tip to first block.

Would it be possible to execute only once all these steps but last one and cache results between tests?
Last step should not be cached, as we can use `preSetup` to pass transactions that should be executed before Clarinet set's chain tip to 1.

On my quite old machine execution of empty test takes ~350-550ms. And I'm sure caching initial chain state would cut this time at least in a half.

**Comment by lgalabru** [comment]
Addressed with latest
