### ISSUE TITLE
Rename "hyperchains" to "subnets"

### ISSUE THREAD

**Issue by obycode** [hirosystems/clarinet#593]
Coordinate this with the hirosystems/stacks-subnets#162

**Comment by lgalabru** [comment]
This refactoring was done with 1.0.0.
The only remaining item is updating the name of the contract that @pavitthrap is manually deploying.

**Comment by lgalabru** [comment]
The remaining `hyperchains` artifacts were fixed in `v1.5.0` I believe. Thanks @obycode!
