### ISSUE TITLE
Add extension to Open VSX public registry

### ISSUE THREAD

**Issue by ceramicwhite** [hirosystems/clarinet#597]
Can we add the extension to [Open VSX](https://github.com/eclipse/openvsx) public registry?

So that the extensions is available on [Code-Server](https://github.com/coder/code-server)

Instructions to publish to OVSX are here: https://github.com/eclipse/openvsx/wiki/Publishing-Extensions

Thanks

**Comment by hugocaillard** [comment]
Hey @ceramicwhite 
Thanks for your suggestion and your review on Open VSX!

It was originally published by the Open VSX team itself, but from now on we'll publish the update on Open VSX along with the ones on the official marketplace!
