### ISSUE TITLE
autocomplete takes only the word after the last '-'

### ISSUE THREAD

**Issue by BowTiedDeployer** [hirosystems/clarinet#599]
for reference, the flow when using the autocomplete:
1. write part of first word and autocomplete everything with enter
2. directly overwrite the second word
3. press tab and overwrite the third word

problem case: 
I wrote `define-private`, wanted to change to `define-public` cause it was miss picked when fast tabbing 
press ctrl-z to undo and looks like in the 2nd line, then added letter `u` and tabbed and got this 

```
(define-private func-name body)
define-p
define-(define-public func-name body)
```

p.s. it is because of it picking `define-public` just from the word `pu` not `define-pu` which is counterintuitive

**Comment by hugocaillard** [comment]
@BowTiedDeployer the fix has been merged, I'll release a new version of the extension tomorrow
