### ISSUE TITLE
Release artefacts missing extension

### ISSUE THREAD

**Issue by MarvinJanssen** [hirosystems/clarinet#60]
https://github.com/hirosystems/clarinet/releases/tag/v0.14.0

.zip is missing from the builds.

**Comment by lgalabru** [comment]
Should we also prefix the binaries names with `clarinet-` ?

**Comment by CharlieC3** [comment]
Fixed binaries for `0.14.0` and `0.14.1`, and updated the release workflow. Thanks for pointing this out @MarvinJanssen!
