### ISSUE TITLE
"Run Test" button for Clarity tests

### ISSUE THREAD

**Issue by obycode** [hirosystems/clarinet#607]
It would be great if VSCode recognized our unit tests as such and added these buttons:

![image](https://user-images.githubusercontent.com/1473715/156463800-b08b7bc8-e142-492d-a14b-6ac1a0e14d73.png)

**Comment by hugocaillard** [comment]
Closing this one, will support from the new approach in #1030

**Comment by obycode** [comment]
Do you mean #1052 or is there a related change in #1030?

**Comment by hugocaillard** [comment]
@obycode I meant 1052 🤦‍♂️
I'll have a few comments to update on like 3 or 4 issues. Thanks
