### ISSUE TITLE
Embed clarity-lsp as a wasm library in the vscode extension

### ISSUE THREAD

**Issue by lgalabru** [hirosystems/clarinet#612]
With Microsoft releasing github.dev and vscode.dev, I think we should revisit the overall architecture of this project.
Instead of having a js extension downloading a `clarity-lsp` binary after the extension installation , the build process should bake a wasm library that can be embedded in the extension itself. With that, the extension would become self sufficient and compatible with online versions of VSCode.

Relevant links:
https://code.visualstudio.com/api/extension-guides/web-extensions
https://github.com/Microsoft/vscode-languageserver-node
https://john-millikin.com/extending-vscode-with-webassembly

**Comment by hugocaillard** [comment]
Done 👍
