### ISSUE TITLE
[BC] v0.14.0 changed command signature for runing single test file 

### ISSUE THREAD

**Issue by LNow** [hirosystems/clarinet#62]
Prior v0.14.0 we were able to run single test file like this: 
```sh
$ clarinet test ./tests/some_test_file.ts
```

v0.14.0 forces us to use very weird syntax:
```sh
$ clarinet test -- ./tests/some_test_file.ts
```

I'm not sure if this BC was intentional or not, but new syntax feels unnatural and it hasn't been communicated anywhere.

**Comment by lgalabru** [comment]
Probably a regression introduced with the manifest-file option, I'll have a look.

**Comment by lgalabru** [comment]
Addressed in latest `main` branch
