### ISSUE TITLE
Deno: Test lib improvements ideas

### ISSUE THREAD

**Issue by hugocaillard** [hirosystems/clarinet#627]
Improvement ideas for the clarinet test lib following #618 

- [ ] `.expect<...>Event` methods will always throws the same error messages (`Unable to retrieve expected <...> Event`)  which make them hard to debug (see #540)
- [ ] `.expect<...>Event` methods expects all the event to be emitted from the same contract (see #540)
- [ ] `.expectPrincipal()` expects a leading `'` instead of the raw value, which is inconsistent with other `expect<Type>()` methods ([comment)](https://github.com/hirosystems/clarinet/pull/618#discussion_r1000422603)
- [ ] `.expectList()` expects something in the form of `"[1, 2, 3]"`, so types.list(...).expectList(...) will always throw. Which is inconsistent with other `expect<Type>()` methods ([comment)](https://github.com/hirosystems/clarinet/pull/618#discussion_r1000421230)

**Comment by lgalabru** [comment]
Related: https://github.com/hirosystems/clarinet/issues/258

**Comment by hugocaillard** [comment]
Closing in favor of clarinet-sdk https://github.com/hirosystems/clarinet/issues/1065
