### ISSUE TITLE
LSP: introduce "current_editor_contract_state"

### ISSUE THREAD

**Issue by hugocaillard** [hirosystems/clarinet#630]
The Clarity LSP fully relies on the `EditorState`, which represents the state of all the contracts (and manifest) on the **File System**. For some features, we want to consider the content of the file currently opened in the editor, **including the unsaved changes**.

## Current behavior
Every time the LSP client sends a request or a notification, the server will try to acquire read or write on the sate `RwLock<EditorState>`.  Notifications and Requests are even competing for it.
In the first naive implementation of the DocumentSymbols request (#626) the idea was to rely on the `EditorState`, leading to significant number of request try to read the state, and potentially outdated data if the file contains unsaved changes.

## Expected behavior
- Some request such as Document Symbols should rely on up to date data and not on possibly outdated data from the file system.
- On Server initialization, the Client shouldn't have to wait for the whole state to be computed to send requests

## Solution
Along with the `editor_state_lock`, implement a `current_editor_state_lock` that only keeps track of the file being currently modified, including the **unsaved change**.
This current state would be updated on `DidOpenTextDocument` and `DidChangeTextDocument`.
It will be requested on Document Symbols requests, Inlay Hints requests.
Advantages:
- Symbols and Inlay Hints will live (up to date we the current changes being made on the document)
- Less competition to acquire read on the `editor_state_lock`
- Symbols, Hover, Inlay hints (and probably more requests would give up to date data based in the current state of an edited/unsaved contract

## Risks
- How does `DidOpenTextDocument` when multiple contracts are open side by side?
- The concurrency when update `editor_state_lock` and `current_editor_state_lock` might lead to some minor issues
- If the contract has dependencies, we might still need to read the `editor_state` to get Inlay Hints data

**Comment by lgalabru** [comment]
Now that we have a working full loop, I think that we starting to think more about "partial analysis" (tracked here https://github.com/hirosystems/clarinet/issues/604) could be a great avenue of optimization.

**Comment by hugocaillard** [comment]
I think #604 is an optimization of the current behavior, that's is needed, and kind of pairs with this one but these are slightly different.

This one is about differentiating dirty files from saved ones.
Let's say _contract1.clar_ exposes a `get_id` function, called from other contracts. If the function is renamed to `get_ids` (but unsaved), we don't want to display diagnostic errors in other contracts (until _contract1.clar_ is saved).
But the auto-completion request, within _contract1.clar_ should provide `get_ids`.

That's the default behavior of rust-analyzer.
Typescript on the other hand works differently (by default) it displays all diagnostics live (onDidChange and onDidSave), but only on file opened in a tab, which is super confusing because a project can have errors but VSCode want show if a file isn't opened. (It's also confusing that some tabs can get red while another one is being edited)
