### ISSUE TITLE
LSP: intellisense fallback when editor_state is locked

### ISSUE THREAD

**Issue by hugocaillard** [hirosystems/clarinet#631]
## Problem

The LSP server initialization (when a contract or manifest is opened) can take some time. During this time, the `editor_state` is not ready and locked. In this case, the Completions request can not be completed. Resulted in two issues:
- on project initialization, it can take some time for developers to get Completion responses,
- if for some reason, the editor_state is locked while a developer is typing, some Completion requests might be missed.

## Expected Behavior

Always send Completions items when requested. 

## Solution

The Server should be more resilient regarding the status of the `editor_state_lock` (being initialized or locked). 
On Completion request, if the `editor_state` is locked, respond with the default completion items.

**Comment by lgalabru** [comment]
I don't think this is the case today, but turning the default completion items into a lazy static constant could also be a good optimization.

**Comment by hugocaillard** [comment]
Partially done in #670 
Can be improved with #668 (need to know the clarity version of a contract as early as possible in the process).
Closing for now following the work in 670
