### ISSUE TITLE
LSP: server crash if invalid tuple

### ISSUE THREAD

**Issue by hugocaillard** [hirosystems/clarinet#644]
The following (invalid) code makes the server crash
```clarity
(define-read-only (get-tuple) (ok { id })
```
With this error:

> clarity extension initialized
> panicked at 'index out of bounds: the len is 1 but the index is 1', components/clarity-repl/src/analysis/ast_visitor.rs:2457:65

**Comment by hugocaillard** [comment]
@obycode What would be your approach regarding that one?
I tried something like so be it really messes with the ast
```rs
tuple_map
    .insert(pair[0].match_atom(), pair.get(1).unwrap_or(&DEFAULT_EXPR));
```

https://github.com/hirosystems/clarinet/blob/develop/components/clarity-repl/src/analysis/ast_visitor.rs#L2457

**Comment by obycode** [comment]
I would probably either do what you have, or just skip that pair:
```rust
                    for element in args {
                        let pair = element.match_list().unwrap_or_default();
                        if pair.len() == 2 {
                          tuple_map.insert(pair[0].match_atom(), &pair[1]);
                        }
                    }
```

**Comment by hugocaillard** [comment]
Both ideas result in this kind of behaviour
<img width="437" alt="Screenshot 2022-11-15 at 14 46 46" src="https://user-images.githubusercontent.com/911307/201935434-fb2dfdb4-36ea-4f8e-b84f-4703d57d7dda.png">

**Comment by obycode** [comment]
Those are coming from the parser, before reaching the ASTVisitor code. That's the parser attempting (poorly it seems) to continue past the error so that more analysis can be done.

**Comment by obycode** [comment]
We can improve on that after 2.1, since this type of change will not be consensus breaking. The node fails on the first error, and does not attempt to use placeholders to continue and parse more. It's just the parse mode that clarinet uses that does this.

**Comment by hugocaillard** [comment]
Ok I move it back in todo then 👌
