### ISSUE TITLE
'contract new' command throws 'thread main' panic error (Clarinet v1.0.5 / Windows 10)

### ISSUE THREAD

**Issue by vysegrad** [hirosystems/clarinet#646]
Creating a new contract with Clarinet v 1.0.5 in Visual Code on Windows 10 returns the following:

> clarinet contract new hellow11
Created file contracts/hellow11.clar
Created file tests/hellow11_test.ts
Updated Clarinet.toml with contract hellow11
thread 'main' panicked at 'not implemented', components\clarinet-files\src/lib.rs:238:17
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

Note: the contract files are in fact created, but relaunching 'clarinet console' does not list the newly created contract under 'Contract identifier'.

**Comment by lgalabru** [comment]
I was unable to reproduce this issue with the latest (1.3.0) on Windows 11, feel free to re-open if you're still experiencing this issue.
