### ISSUE TITLE
Can't run clarinet release binary in OSX

### ISSUE THREAD

**Issue by CharlieC3** [hirosystems/clarinet#67]
A user reported they cannot run `clarinet` after downloading the binary from the releases page.

![unknown](https://user-images.githubusercontent.com/2747302/124327556-18856d80-db56-11eb-8b09-275db7213b12.png)

**Comment by CharlieC3** [comment]
For now users can run `xattr -d com.apple.quarantine /path/to/downloaded/clarinet/binary` in the terminal to resolve the issue.

**Comment by MarvinJanssen** [comment]
After been greeted by the popup, a user can also go to: System Settings > Security & Privacy > General tab > Click "Open Anyway" (Might have to click the lock symbol on the bottom left first.)

Although I do not think it is necessary for running Clarinet from the command line.

**Comment by CharlieC3** [comment]
Doesn't seem like there's any way around this when downloading an unsigned file from the internet using a browser on macos. Even when uploading the artifact without the attribute to Github, the MacOS system will add it on for anyone downloading the zip or raw binary via their browser. The currents solutions are to either:

1. Sign the binary and get it notarized by Apple during the release process. Feasible, but will require a sizable amount of work.
2. Submit the binary to homebrew. Users installing the binary through homebrew will bypass the attribute getting added on. Just need 7 more watcher then this is attainable.

@lgalabru Thoughts?

**Comment by MarvinJanssen** [comment]
I think MacPorts does not have such a requirement https://www.macports.org.

Nonetheless, if we are a mere 7 watchers away then let us do a quick social push.

**Comment by lgalabru** [comment]
Agreed, let's push for option 2

**Comment by CharlieC3** [comment]
Looks like a user is already working on it: https://github.com/Homebrew/homebrew-core/pull/80745
Thanks @alebcay !

**Comment by CharlieC3** [comment]
Homebrew-core now officially supports `clarinet` installs! Closing this issue.
