### ISSUE TITLE
LSP: Improve completion

### ISSUE THREAD

**Issue by hugocaillard** [hirosystems/clarinet#670]
- [x] Rework the completions to directly use lsp_types instead of going through intermediary custom types
- [x] Move the completions related code into its own file under lsp/src/common/request/
- [x] Improve parenthesis handling
- [x] Propose keywords based on the clarity version of the contract
- [x] Suggest clarity 2 aliases instead of v1 version (`element-at?`, `index-of?`) 
- [x] Improve snippets handling, developer currently have to delete the snippets keyword before actually typing code
- [x] Autocomplete constants
- [x] Auto-complete variables, maps, fts, nfts (with completion choices)
- [x] Auto complete let binding and function parameters

**Comment by lgalabru** [comment]
> Rework the completions to directly use lsp_types instead of going through intermediary custom types
Let's talk about this during our next meeting, this is a bit touchy.

**Comment by lgalabru** [comment]
Related https://github.com/hirosystems/clarinet/issues/567
