### ISSUE TITLE
Support for more package manager (apt, macport)

### ISSUE THREAD

**Issue by MarvinJanssen** [hirosystems/clarinet#68]
I wanted to create a single issue to track package manager support.

- [x] Homebrew (macOS) - https://github.com/Homebrew/homebrew-core/pull/80745
 	- [Requires >=30 forks, >=30 watchers and >=75 stars](https://github.com/Homebrew/brew/blob/master/docs/Acceptable-Casks.md).
- [x] Winget (Windows)
- [ ] Apt (Linux)
- [ ] MacPorts (macOS)
	- [Should be an easy win](https://guide.macports.org/#development).

Feel free to amend this issue.

**Comment by MarvinJanssen** [comment]
PR for Homebrew (macOS): https://github.com/Homebrew/homebrew-core/pull/80745.

**Comment by lgalabru** [comment]
Looking at package managers on windows

- https://github.com/lukesampson/scoop: 13.6k ⭐️
- https://github.com/chocolatey/choco: 7.6k ⭐️

Should we use stars as a proxy for priority?

**Comment by lgalabru** [comment]
As pointed by @zone117x in another channel, going on the `winget` path might actually be more mainstream, since this package will be available by default on every single windows 10 machine: https://devblogs.microsoft.com/commandline/windows-package-manager-1-0/

**Comment by MarvinJanssen** [comment]
Agreed.

**Comment by CharlieC3** [comment]
Winget support is completed!
https://github.com/hirosystems/clarinet/blob/develop/README.md#install-from-winget-windows

**Comment by lgalabru** [comment]
![1](https://user-images.githubusercontent.com/87777/126259955-a7f12c8b-fd24-4ee2-8ede-2dbc05f9724f.png)

**Comment by agraebe** [comment]
Recent developer feedback indicates that windows devs want support for other package managers. Choco (https://github.com/chocolatey/choco) came up as a suggestion

**Comment by smcclellan** [comment]
Closing this one due to age. I'm happy to revisit if interest resurfaces.
