### ISSUE TITLE
Github Action producing a corrupted docker image

### ISSUE THREAD

**Issue by lgalabru** [hirosystems/clarinet#697]
Per https://github.com/hirosystems/clarinet/issues/695#issuecomment-1336197482, it looks like the last CI workflow ended up producing a corrupted image of clarinet.
@CharlieC3 / @aravindgee have you seen this issue on other repos? I don't think we touched that dockerfile recently.
The error can be observed here: https://github.com/lgalabru/clariswap/actions/runs/3609712856/jobs/6083073294
Trace:
```
Run docker://hirosystems/clarinet:latest
/usr/bin/docker run --name hirosystemsclarinetlatest_d0a57e --label 290506 --workdir /github/workspace --rm -e "INPUT_ARGS" -e "HOME" -e "GITHUB_JOB" -e "GITHUB_REF" -e "GITHUB_SHA" -e "GITHUB_REPOSITORY" -e "GITHUB_REPOSITORY_OWNER" -e "GITHUB_RUN_ID" -e "GITHUB_RUN_NUMBER" -e "GITHUB_RETENTION_DAYS" -e "GITHUB_RUN_ATTEMPT" -e "GITHUB_ACTOR" -e "GITHUB_TRIGGERING_ACTOR" -e "GITHUB_WORKFLOW" -e "GITHUB_HEAD_REF" -e "GITHUB_BASE_REF" -e "GITHUB_EVENT_NAME" -e "GITHUB_SERVER_URL" -e "GITHUB_API_URL" -e "GITHUB_GRAPHQL_URL" -e "GITHUB_REF_NAME" -e "GITHUB_REF_PROTECTED" -e "GITHUB_REF_TYPE" -e "GITHUB_WORKSPACE" -e "GITHUB_ACTION" -e "GITHUB_EVENT_PATH" -e "GITHUB_ACTION_REPOSITORY" -e "GITHUB_ACTION_REF" -e "GITHUB_PATH" -e "GITHUB_ENV" -e "GITHUB_STEP_SUMMARY" -e "GITHUB_STATE" -e "GITHUB_OUTPUT" -e "RUNNER_OS" -e "RUNNER_ARCH" -e "RUNNER_NAME" -e "RUNNER_TOOL_CACHE" -e "RUNNER_TEMP" -e "RUNNER_WORKSPACE" -e "ACTIONS_RUNTIME_URL" -e "ACTIONS_RUNTIME_TOKEN" -e "ACTIONS_CACHE_URL" -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/clariswap/clariswap":"/github/workspace" hirosystems/clarinet:latest test --coverage --manifest-path=./protocol/Clarinet.toml
clarinet: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by clarinet)
clarinet: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by clarinet)
clarinet: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by clarinet)
```

**Comment by CharlieC3** [comment]
Looks like the `latest` tag is being used here. This tag gets [updated regularly](https://hub.docker.com/layers/hirosystems/clarinet/latest/images/sha256-e7a2c1fa0aa0ad83f45c8138196850bf43ece9304240eeeaa7ad96af9fbfeabd?context=repo) with the current setup in CI. It's likely that the upstream base image was updated and a version of GLIBC was removed.

Can you change the tests to use a specific Docker tag version instead of `latest`? Otherwise you may have to update the Dockerfile to lock in to an upstream base image version with the GLIBC version you need.

**Comment by lgalabru** [comment]
> This tag gets [updated regularly](https://hub.docker.com/layers/hirosystems/clarinet/latest/images/sha256-e7a2c1fa0aa0ad83f45c8138196850bf43ece9304240eeeaa7ad96af9fbfeabd?context=repo) with the current setup in CI. It's likely that the upstream base image was updated and a version of GLIBC was removed.

Yep, we produced a release of Clarinet, and developers are using the `latest` tag, to make sure that the CI of their repos are always checked with the latest version of Clarinet, which is I think what we want. 

This docker images are built by the GitHub actions of this repo, from what I see it takes a `clarinet` binary built on a bare `ubuntu-latest` vm and copy it in a `debian:bullseye-slim` image.  
Are you saying that we should force a glib install in that container https://github.com/hirosystems/clarinet/blob/develop/dockerfiles/ci/clarinet.dockerfile, that is aligned with the one being used on the bare `ubuntu-latest` vm ran by the job runner? Can we go further and ensure that the 2 systems are using the same version of GLIBC?
Could @aravindgee help us with that? That'd be high priority on our end - this is breaking every single repo using Clarinet as a CI.

**Comment by lgalabru** [comment]
Addressed here https://github.com/hirosystems/clarinet/pull/700.

**Comment by CharlieC3** [comment]
@lgalabru going through all the releases of the Clarinet docker image over the past couple of months, I'm not seeing GLIBC 2.32 - 2.34 installed in any of them.
`docker run --platform=linux/amd64 --entrypoint=/bin/bash hirosystems/clarinet:1.0.X -c "ls -la /lib/x86_64-linux-gnu/libc.so.6"` (replace X in tag)

From my perspective it doesn't appear like the GLIBC version installed in the Clarinet image has changed with the most recent `latest` tag. However, I would advise that the `FROM` directive in all dockerfiles in this repo lock to a specific tag (e.g. `debian:bullseye-20221114-slim`)

**Comment by CharlieC3** [comment]
@lgalabru Nice! Done
https://hub.docker.com/layers/hirosystems/clarinet/latest/images/sha256-dbe3e6c0afd526071cc5aa9632262fd9b13e5f591d790c87be0a9294bd0bafd1?context=explore

**Comment by lgalabru** [comment]
Perfect thanks @CharlieC3! @ummarikram you should be good to go!
