### ISSUE TITLE
Installing Clarinet on Linux

### ISSUE THREAD

**Issue by whoabuddy** [hirosystems/clarinet#7]
This is amazing, thank you!

When installing on Linux Mint (based on Ubuntu), I ran into a a few errors when I ran `cargo install clarinet`.

The main one was `linker 'cc' not found`.

To fix, I installed the same prereqs I used when building a miner, although I think `build-essential` may be the only one I needed.

https://github.com/AbsorbingChaos/stx-miner-script/blob/master/config-miner-krypton.sh#L51

Would it be worth adding a note to the readme?

**Comment by lgalabru** [comment]
Yes I'll add this as a pre-requisite, thank you for this insight!

**Comment by JBotwina** [comment]
I can confirm that in addition to build-essential, you also need pkg-config and libssl-dev on Linux (wsl2- Ubuntu)
