### ISSUE TITLE
Incorporate Deno 1.28 npm import features

### ISSUE THREAD

**Issue by hstove** [hirosystems/clarinet#702]
Deno 1.28 came with the really cool feature of supporting NPM imports. I find this really helpful, and there are a few NPM packages (like `micro-stacks`, `bitcoinjs-lib`, etc) that I would really like to use in my tests. At the moment, I have to do some hacky workarounds when I need to use a NPM package that I can't easily re-write.

I know there were some changes around how Deno is vendored, but I'm not able to parse how that works in Clarinet exactly. Is `deno_graph` the relevant dependency here? I tried updating that to latest, but that threw a few errors when building.

**Comment by hstove** [comment]
Hey - curious what the outlook for this is? I have no idea how the internals of Clarinet's Deno code works, so I'm not sure how big of a lift this is. I find myself wanting this feature more and more. For example, I have code that does things like generate a Bitcoin payload or signed message, and the only good libraries are on NPM. Right now, I have to have separate scripts (even in Deno!) that create mock data, which I can separately import into my tests. It's just a hassle and I'd love to be able to do this without separate scripts.

**Comment by hugocaillard** [comment]
Still kind of relevant, but will be handled with the approach in #1030 
Closing this one
(Let me know if you have feedback regarding #1030 @hstove 🙏 )
