### ISSUE TITLE
Malloc error clarity-repl

### ISSUE THREAD

**Issue by nixfreak** [hirosystems/clarinet#706]
System: MacBook Pro (Retina, 15-inch, Mid 2015)
Term: Kitty kitty 0.26.5 created by Kovid Goyal

```
Carity-repl v0.33.2
Enter "::help" for usage hints.
Connected to a transient in-memory database.

>> (* 5 4 (- (5))
(.. 
(.. )
clarity-repl(88037,0x10f249600) malloc: *** error for object 0x6000022f0680: pointer being freed was not allocated
clarity-repl(88037,0x10f249600) malloc: *** set a breakpoint in malloc_error_break to debug
[1]    88037 abort      clarity-repl
```

I can also get this pointer issue using Term shell also.

**Comment by lgalabru** [comment]
Thanks for opening this issue @nixfreak. I would recommend using the latest version of clarinet (`v1.2.0`).
Feel free to reopen this issue if you're still experiencing it after upgrade.
