### ISSUE TITLE
Bug testing Clarity 2 contracts in v1.2.0

### ISSUE THREAD

**Issue by hstove** [hirosystems/clarinet#709]
Previously, I was able to write and test Clarity 2 contracts using Clarinet without issues. However, with 1.2.0, there's been a regression. When running a test that calls a Clarity 2 function, you get the error:

```
Unchecked(CostComputationFailed("Error evaluating result of cost function ST000000000000000000002AMW42H.costs.cost_slice: Unchecked(UndefinedFunction(\"cost_slice\"))"))
```

Not just for `slice?`, but for all Clarity 2 functions.

I have a demo project that reproduces this: https://github.com/hstove/clarinet-repro-cost-bug

Run `clarinet test tests/tester_test.ts` to repro

**Comment by lgalabru** [comment]
Addressed with `v1.3.0`. Thanks for your help on this @hstove!
