### ISSUE TITLE
Question: Prettier Support

### ISSUE THREAD

**Issue by dabuchera** [hirosystems/clarinet#727]
Is there anyone working on Prettier Support for Clarity?

https://prettier.io/docs/en/plugins.html

**Comment by lgalabru** [comment]
Hey @dabuchera! That'd be a cool initiative. No one at hiro is working on this, we will be working on https://github.com/hirosystems/clarinet/pull/664 when we have more bandwidth (so probably after 2.1), that could help this project.

**Comment by lgalabru** [comment]
Will close this issue, @dabuchera let us know if there's anything we can do!

**Comment by dabuchera** [comment]
Hi @lgalabru 
Will work on it if I find some time. Thanks for the support.
