### ISSUE TITLE
Update default contract template

### ISSUE THREAD

**Issue by whoabuddy** [hirosystems/clarinet#730]
I just started a quick test project to mock something up, and I think the default contract comments should be expanded a bit.

The default contract lists out in the comments:

- title
- description
- constants
- data maps and vars
- private functions
- public functions

The first thing I see missing is read-only functions, and this is the template we've adopted for CityCoins (also based on xDAO):

- title
- version
- synopsis
- description
- traits
- token definitions
- constants
- data vars
- data maps
- public functions
- read only functions
- private functions

I think there was a SIP related to this topic as well, it'd be nice to get in alignment on best practices especially when a lot of people will be generating contract code from this tool!

**Comment by lgalabru** [comment]
@whoabuddy if you add a clarity template to add to this issue, I'd be happy to slip this change in a future release.
You can also update this file https://github.com/hirosystems/clarinet/blob/74bb1cae3656c757455944aef88997d278f8b64d/components/clarinet-cli/src/generate/contract.rs#L44-L57 and open a PR :).

**Comment by lgalabru** [comment]
Addressed in `v1.3.1`.
