### ISSUE TITLE
Some commands missing in the help output

### ISSUE THREAD

**Issue by csgui** [hirosystems/clarinet#738]
While working with the `clarity-repl` I figured out that some commands are missing in the help information.

`get_epoch`
`encode`
`decode`

Is that a known issue or is it mean to be like that?

<img width="909" alt="image" src="https://user-images.githubusercontent.com/13015/208920382-ec211e04-0b7e-47e3-9aa0-cabc3bf042d7.png">

Cheers!

**Comment by lgalabru** [comment]
Thanks for opening this issue @csgui, this missing docs are bugs, not features.
