### ISSUE TITLE
::get_costs command (without an argument) is panicking in clarity-repl

### ISSUE THREAD

**Issue by csgui** [hirosystems/clarinet#745]
Running `::get_costs` command without any expression is issuing a panic!

To Reproduce:

1. without arguments or expression to the command.
`>>::get_costs` -> panic!

2. passing an empty space to the command.
`>>::get_costs ` -> working

3. passing a number to the command.
`>>::get_costs 15` -> working

Reproducible with the last clarinet version (1.3.0).

**Comment by lgalabru** [comment]
Addressed in `v1.3.1`, thank you for your help @csgui!
