### ISSUE TITLE
Deployment plan documentation doesn't cover contract call

### ISSUE THREAD

**Issue by pki-acs** [hirosystems/clarinet#747]
A blog post about deployment plans advertises that they can be used to perform STX transfers and contract calls. However no documentation / examples can be found for both use cases. Esp. it is not clear how to pass contract call parameters in deployment plan. Parameters seem to deserialize to Vec<String> but how does one input i.e. optional principal parameter in .yaml file?

**Comment by lgalabru** [comment]
Addressed in https://github.com/hirosystems/clarinet/pull/798
