### ISSUE TITLE
Homebrew repository is gone

### ISSUE THREAD

**Issue by victorcoder** [hirosystems/clarinet#76]
`fatal: repository 'https://github.com/hirosystems/homebrew-clarinet/' not found`

**Comment by CharlieC3** [comment]
> `fatal: repository 'https://github.com/hirosystems/homebrew-clarinet/' not found`

Hey @victorcoder, the docs are outdated and will be updated soon. You can now install `clarinet` from the official homebrew repo via:
```
brew update
brew install clarinet
```
