### ISSUE TITLE
Add publishing of multi-arch docker images to CI pipeline

### ISSUE THREAD

**Issue by janniks** [hirosystems/clarinet#854]
I'm getting the following error (and clarinet termination) when running the stacks-billboard example.

```
error: unable to create container: API responded with a 404 not found: {"message":"No such image: hirosystems/stacks-blockchain-api:latest"}
```

**UPDATE**:
A preferred fix would be to update a few CI/CD pipelines and produce multi-arch images

**Comment by lgalabru** [comment]
Thanks for opening this issue @janniks. We have a short term patch in `v1.4.1`.
A preferred fix would be to update a few CI/CD pipelines and produce multi-arch images, but this could take some time.

**Comment by aravindgee** [comment]
Hi folks, this Issue (and anything else Clarinet related) may take time as I'm more focussed on Artemis with the upcoming launch. If there's a pressing need, let me know and we can reprioritize as needed.

**Comment by aravindgee** [comment]
Hi @janniks , I noticed that this issue is still in our backlog and wanted to check-in. Does this item still require attention?

**Comment by janniks** [comment]
I think this is fixed, closing
