### ISSUE TITLE
Clarify use of deployment plans to wait for blocks

### ISSUE THREAD

**Issue by friedger** [hirosystems/clarinet#860]
I'd like to setup a devnet with 1 bitcoin transaction (that can later be used to verify with clarity-bitcoin-lib)

I tried to develop a deployment plan that waits for a few blocks before the bitcoin transaction is published, however, it looks like the bitcoin tx is broadcasted in the first block, because I see an error message `Unable to retrieve UTXOs`

The code is here:
https://github.com/friedger/clarity-bitcoin/tree/feat/2.1

**Comment by lgalabru** [comment]
Thanks for opening this issue @friedger!
I just had a look at your repo, we're almost there. In your `Devnet.toml` you need to uncomment the line 118
```tool
enable_next_features = true
```

After completing this step, I was able to run:
```
$ clarinet integrate
$ clarinet deployment apply -p deployments/sent-to-first-input.devnet-plan.yaml --no-dashboard
```

Please let me know how that goes for you!

**Comment by friedger** [comment]
I was hoping to get a deterministic behaviour. 

Alternatively, I'd like to mock values of `get-*-info?` in simnet. In particular for the bitcoin block header hash.

**Comment by lgalabru** [comment]
The initial question was addressed, feel free to re-open an/this issue if you want to follow-up.
