### ISSUE TITLE
Add links in `clarinet --help`

### ISSUE THREAD

**Issue by obycode** [hirosystems/clarinet#871]
It would be helpful if the `--help` info included a link to documentation and a link to open an issue on GitHub.

**Comment by lgalabru** [comment]
Add a link to https://docs.hiro.so/clarinet/introduction?

**Comment by obycode** [comment]
Maybe also a link to create a new issue? https://github.com/hirosystems/clarinet/issues/new/choose

**Comment by MicaiahReid** [comment]
Looks like @LakshmiLavanyaKasturi already took care of this in #893. Great work Lavanya!
