### ISSUE TITLE
Integration with Github workflow suggestion

### ISSUE THREAD

**Issue by lgalabru** [hirosystems/clarinet#884]
It'd be great to suggest clarinet-based workflow, when detecting clarinet projects.

<img width="2111" alt="Screenshot 2023-02-13 at 10 08 59" src="https://user-images.githubusercontent.com/87777/218495991-62168b82-7c33-4ab7-a0b0-fe41e6bfb67c.png">

**Comment by hugocaillard** [comment]
With the clarinet-sdk, it does suggest the Node.js workflow with `npm test` out of the box 👍
