### ISSUE TITLE
Warn users if local contract is not listed in `depends_on`

### ISSUE THREAD

**Issue by friedger** [hirosystems/clarinet#90]
Even though well tested with `clarinet console`, the deployment on mainnet fail due to missing contract

In my project I have a local contract called `clarinet-bitcoin` and a requirement for similar contract. On contract used both contract accidentally. The clarinet console test worked because of the local contract.

Relevant project: https://github.com/friedger/clarity-friedger-pool/blob/92843c10a4c5669eb1355dcea51aea0d0a37e368/Clarinet.toml

See also https://github.com/blockstack/explorer/issues/492

**Comment by lgalabru** [comment]
Thanks @friedger!

**Comment by zone117x** [comment]
Time travel to https://github.com/blockstack/clarity-js-sdk/issues/31 🙂

**Comment by lgalabru** [comment]
Yeah by the way, I think we're now at a point where we could get rid of the `depends_on` attribute - I implemented an analysis pass in the REPL for this a few weeks ago.

**Comment by MarvinJanssen** [comment]
Awesome!

**Comment by obycode** [comment]
Additional changes have been made related to dependencies recently. #333 is also related. I think this can be closed now.

**Comment by lgalabru** [comment]
Closing now, as `depends_on` attributes are no longer required in `Clarinet.toml` files.
