### ISSUE TITLE
Improve debugability of chain.mine_block() 

### ISSUE THREAD

**Issue by lgalabru** [hirosystems/clarinet#91]
When chain.mine_block receives a transaction that does not have the right number of arguments, it raises an exception that looks like this:
```
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: ("Analysis error: expecting 3 arguments, got 2", Some(Diagnostic { level: Error, message: "expecting 3 arguments, got 2", spans: [Span { start_line: 1, start_column: 1, end_line: 1, end_column: 127 }], suggestion: None }))', src/test/deno.rs:855:22
34
```
Instead, it should hint developers, and point a finger to the guilty transaction.

**Comment by obycode** [comment]
See #183 for another example that needs improved debugability. In this case, the type of one of the arguments was wrong and `mine_block` just silently fails, leaving no receipts in the block.

**Comment by lgalabru** [comment]
Related: https://github.com/hirosystems/clarinet/issues/407

**Comment by lgalabru** [comment]
Addressed with latest
