### ISSUE TITLE
Revive cbtc example to a working state

### ISSUE THREAD

**Issue by sabbyanandan** [hirosystems/clarinet#911]
The [cbtc](https://github.com/hirosystems/clarinet/tree/develop/components/clarinet-cli/examples/cbtc) example needs to be revised. Since this example is repurposed in docs, blogs, and other outbound collateral, let's ensure the instructions are up-to-date and it continues to help with the learning.

Aside from this example, the other Chainhook example also needs TLC (see: https://github.com/hirosystems/chainhook/issues/218).

At least in `cbtc`, the instructions in README don't reflect the latest changes in the YAML. For instance, the BTC addresses have changed, but the README points to the old ones.

The sample functions included in the Serverless app start successfully; however, the invocation of the wrap/unwrap functions error with a 404. Also, the `--printOutput` option was removed by the Serverless folks in the latest major release, so without no logs, it is hard to understand or debug the reasons behind 404.

**Comment by lgalabru** [comment]
Addressed in v1.5.0.
