### ISSUE TITLE
Deploy to and interact with subnet in deployment plans

### ISSUE THREAD

**Issue by obycode** [hirosystems/clarinet#916]
It would be nice to be able to specify in Clarinet.toml that a contract should be deployed on the subnet. Similarly, in a deployment plan, we should be able to specify contracts to deploy and transactions to be sent to the subnet.

**Comment by kantai** [comment]
One stumbling block to be aware of for deploying on the subnet is that the deployment plan will need a STX balance in the subnet in order to deploy the contract (this should be done through a STX deposit).

**Comment by hugocaillard** [comment]
Closing as not planned for now. Might reopen after nakamato
