### ISSUE TITLE
Websockets endpoint not working (?)

### ISSUE THREAD

**Issue by 2snEM6** [hirosystems/clarinet#920]
I might be doing something wrong but I am unable to make the websockets endpoint work. Everything else from the API works fine.

I am trying to connect to `ws://localhost:3999/extended/v1/ws/`

See: 
![image](https://user-images.githubusercontent.com/7485885/223428647-109d81a0-aef5-4353-9486-d8b1d8c189da.png)

**Comment by lgalabru** [comment]
@2snEM6 were you able to solve this issue?

**Comment by lgalabru** [comment]
Thanks @2snEM6! will close this issue then.
