### ISSUE TITLE
Bitcoin node not booting properly in clarinet integrate

### ISSUE THREAD

**Issue by PatrionDigital** [hirosystems/clarinet#922]
Issue: local devnet is not working, with both `bitcoin-node` and `stacks-node` stuck in yellow _booting_ status in the clarinet status window

Expected behaviour: bitcoin-node will start generating blocks allowing stacks-node to connect properly

Environment:
- clarinet v1.4.2
- docker desktop v4.17.0
- Windows 11

Notes: both project and docker are fresh installs. I was able to start the devnet on my first try and it worked fine. However, subsequent tries always give the same issue, with the logs looking exactly the same.

[2023-03-09-stacks-bitcoind-log.txt](https://github.com/hirosystems/clarinet/files/10926756/2023-03-09-stacks-bitcoind-log.txt)
[2023-03-09-stacks-stacksd-log.txt](https://github.com/hirosystems/clarinet/files/10926757/2023-03-09-stacks-stacksd-log.txt)
[2023-03-09-stacks-project-logs.zip](https://github.com/hirosystems/clarinet/files/10926759/2023-03-09-stacks-project-logs.zip)

**Comment by lgalabru** [comment]
Action: improve cleaning before re-creating / starting containers.
We should also investigate the very first fun.

**Comment by ummarikram** [comment]
@lgalabru I am facing the same issue.

**Comment by lgalabru** [comment]
This usually happens when your VM runs out of space. @ummarikram could you check this?

**Comment by ummarikram** [comment]
Yes, I think it is a memory issue. Docker tends to take up a lot of ram. I restricted the memory usage for it and it works

**Comment by smcclellan** [comment]
@ummarikram How much RAM ended up working for you here?

**Comment by ummarikram** [comment]
@smcclellan I had to restrict docker with the following settings in the .wslconfig file

```
[wsl2]
memory=1GB   # Replace 4GB with the desired memory limit
processors=2 # Replace 2 with the desired CPU limit
```

**Comment by smcclellan** [comment]
@LakshmiLavanyaKasturi Could you add this to troubleshooting?

**Comment by hugocaillard** [comment]
@MicaiahReid Could this be link to #974

**Comment by MicaiahReid** [comment]
Yes, I think so. A Linux system using the `bind_containers_volumes = true` feature should use a lot less memory. However, on Mac, increasing the amount of memory available to docker is a workaround.

I think all that's left to do here is to add some of this information to our troubleshooting guide.

**Comment by hugocaillard** [comment]
Closing this one.
If similar issues happen again, I recommend opening a new issue referencing this one to make it easier to track
