### ISSUE TITLE
Coverage: line with matching value only counted as untested

### ISSUE THREAD

**Issue by friedger** [hirosystems/clarinet#923]
When the matching value is on a single line the coverage shows this line as not tested:
![image](https://user-images.githubusercontent.com/1449049/224110958-3a7afe79-d2e1-4e6f-b643-7476cb4e8e39.png)

**Comment by lgalabru** [comment]
Thanks for opening this issue @friedger!

**Comment by lgalabru** [comment]
Can we close this issue @hugocaillard?

**Comment by hugocaillard** [comment]
Ah yes, fixed in #1030 (not released yet but soon)
Thx @friedger
