### ISSUE TITLE
Missing type check for argument function

### ISSUE THREAD

**Issue by bolpol** [hirosystems/clarinet#925]
My tests returned an invalid balance, I mixed up the order of the arguments.

We have some functions mint.

```clarity
(define-public (mint (amount uint) (recipient principal))
```

The next call should throw an error invalid encoded argument or something alike.

```ts
    Tx.contractCall(
        "erc-20",
        "mint",
        [
            types.principal(account.address),
            types.uint(amount),
        ],
        sender.address
    );
```
Expected result:

```bash
Type error: ...
```

NOTE: Working code
```ts
    Tx.contractCall(
        "erc-20",
        "mint",
        [
            types.uint(amount),
            types.principal(account.address),
             
        ],
        sender.address
    );
```

Expected result:

```bash
Ok
```

**Comment by lgalabru** [comment]
Strange, that looks like a regression. Thanks for opening this issue.

**Comment by hugocaillard** [comment]
@gfijrb I tried to reproduce with a code similar that your and I do get the error:
` -> expecting expression of type 'uint', found 'principal'`

What is you clarinet version? (`clarinet --version`)? Could you share you test code?
Thanks

**Comment by bolpol** [comment]
> principal

https://github.com/bolpol/clarity-fungible-token/blob/dev/tests/erc-20_test.ts

**Comment by bolpol** [comment]
And an off-topic question where can I join to development discussion?)
