### ISSUE TITLE
Requirements for genesis contracts are not added to default devnet deployment plan

### ISSUE THREAD

**Issue by friedger** [hirosystems/clarinet#927]
**Description**
A contract that uses genesis contracts like SP000.. pox or bns fail to deploy when using devnet

Adding a requirement for SP000...pox does not help.

**Workaround**
Manually change SP00 to ST00 and back when doing integration tests or unit tests. It is a pain.

**Expected behavior**
SP000.. is changed to ST000.. in the contract.

**Additional context**
Testing here: https://github.com/friedger/clarity-xverse/tree/v2.1

**Comment by lgalabru** [comment]
Thanks for opening this issue @friedger! Will set the priority to urgent.

**Comment by lgalabru** [comment]
Addressed in `v1.5.0`

**Comment by friedger** [comment]
@lgalabru My contract is still deployed with SP00 in the code instead of ST00
