### ISSUE TITLE
Keyword highlighting error

### ISSUE THREAD

**Issue by obycode** [hirosystems/clarinet#966]
If a name contains a builtin keyword, e.g. `commit-block-height` contains `block-height`, the name is not highlighted correctly.

<img width="611" alt="image" src="https://user-images.githubusercontent.com/1473715/232593191-fc823d63-55b2-4717-b718-812350997403.png">

**Comment by hugocaillard** [comment]
Some sample code to test.
Will have to fix at the https://github.com/hirosystems/clarity.tmbundle.
This also shows the issue to properly highlight the first argument, will try to tackle this at the same time

```clarity
(define-private (tst (test-block-height uint) (test-tx-sender uint))
  (begin
    (print test-block-height)
    (print test-tx-sender)
  )
)
```
