### ISSUE TITLE
Clarinet requires rust nightly to compile

### ISSUE THREAD

**Issue by CharlieC3** [hirosystems/clarinet#97]
In order for clarinet to stay compliant with homebrew requirements, it must be able to compile on a stable Rust version. [See discussion here for more info.](https://github.com/Homebrew/homebrew-core/pull/82839)

**Comment by lgalabru** [comment]
Ha, I was not aware of this requirement.
To be addressed with https://github.com/hirosystems/clarinet/pull/100
