### ISSUE TITLE
Bug testing Clarity 2 builtin functions 

### ISSUE THREAD

**Issue by jo-tm** [hirosystems/clarinet#971]
Similar bug to #709, builtin Clarity functions show no available cost. There was fix (https://github.com/hirosystems/clarinet/pull/711) but seems not effective.

Can be reproduced by original repo from @hstove (calling `slice`): https://github.com/hstove/clarinet-repro-cost-bug
Or by this one calling `stx-account`: https://github.com/Trust-Machines/pox-clarinet-tests

```clarity
Readonly Contract call runtime error: pox-2::stack-increase(u1000) -> 
 Runtime Error: Runtime error while interpreting ST1J4G6RR643BCG8G8SR6M2D9Z9KXT2NJDRK3FBTK.contract-call:
   Unchecked(CostComputationFailed("Error evaluating result of cost function ST000000000000000000002AMW42H.costs.cost_stx_account: 
    Unchecked(UndefinedFunction(\"cost_stx_account\"))"))
```

Appears on 1.1.0 to 1.5.4 when imported as:

```typescript
import { Clarinet, Tx, Chain, Account, types } from 'https://deno.land/x/clarinet@v1.3.0/index.ts';
```

**Comment by igorsyl** [comment]
@diwakergupta @lgalabru: @jo-tm is using clarinet to text pox-2.clar.

**Comment by obycode** [comment]
I'm not seeing this bug in either of those repos. The [clarinet-repro-cost-bug](https://github.com/hstove/clarinet-repro-cost-bug) tests pass and there are some other issues with the test in [pox-clarinet-tests](https://github.com/Trust-Machines/pox-clarinet-tests), but I don't see that error. Are you using the latest clarinet (1.5.4)?

**Comment by obycode** [comment]
If I log the result from the call to `builtin.getSTXAccount(sender.address)`, I get:

```
{
  session_id: 1,
  result: "{locked: u0, unlock-height: u0, unlocked: u1000000}",
  events: []
}
```

**Comment by jo-tm** [comment]
okey is working now, thanks.
