### ISSUE TITLE
Clarinet still prompts to write files even with --allow-write

### ISSUE THREAD

**Issue by MarvinJanssen** [hirosystems/clarinet#975]
`clarinet run` still prompts to write files even when using the `--allow-write` flag.

```
% clarinet --version
clarinet 1.5.4

% clarinet run --allow-write script.ts
⚠️  ️Deno requests write access to "file-1.txt". Run again with --allow-write to bypass this prompt.
   Allow? [y/n (y = yes allow, n = no deny)]  y
⚠️  ️Deno requests write access to "file-2.txt". Run again with --allow-write to bypass this prompt.
   Allow? [y/n (y = yes allow, n = no deny)]  y
script.ts => running script ... ok (2s)
```

**Comment by diwakergupta** [comment]
> @diwakergupta would you please prio this. It's blocking sBTC testing efforts.

Can you elaborate? I see @MarvinJanssen 's comment that this is blocking a github action but there's not much more detail.

Anyways, @smcclellan could you follow up here? Thanks!

**Comment by smcclellan** [comment]
@MicaiahReid to take a look!

**Comment by MarvinJanssen** [comment]
@diwakergupta it's not blocking sBTC tests _per se_, we just have to manually press Y for every file we generate. But yes it does prevent the GH Action from working.

**Comment by vicnicius** [comment]
Sorry to hijack the issue but https://github.com/hirosystems/clarinet/issues/587 is somewhat related. Not sure if there would be room to tackle both at the same time but I thought it was worth mentioning.

**Comment by MicaiahReid** [comment]
Hey @vicnicius, yes, I'll be including that in #981 as well. Thanks!

**Comment by diwakergupta** [comment]
> @diwakergupta can we please have a minor release for this? we are also using the cool feature of specifying the filename output `--coverage <filename>`, a feature that is in `develop` branch but not in Clarinet 1.5.4. cc/ @MarvinJanssen

Yep I believe a release is being prepped as we speak. Also going forward, please tag @smcclellan, who is the eng manager for the clarinet team.
