### ISSUE TITLE
suggestion: move postgresql for clarinet integrate to a different port

### ISSUE THREAD

**Issue by faried** [hirosystems/clarinet#99]
`clarinet integrate` bombs out early on if there is a copy of postgresql running locally.  It also leaves the terminal in a messed up state (have to run `reset` to fix it).

**Comment by faried** [comment]
Ah, thanks, I'd missed that setting.

That gets closer, but it changes both the external and internal ports in the mapping:

```
$ docker ps -f 'name=postgres.v.devnet'
CONTAINER ID   IMAGE             COMMAND                  CREATED         STATUS         PORTS                                NAMES
a0a86ce02f18   postgres:alpine   "docker-entrypoint.s…"   9 minutes ago   Up 9 minutes   5432/tcp, 0.0.0.0:15432->15432/tcp   postgres.v.devnet
$ 
```

It should be `0.0.0.0:15432->5432`.

**Comment by lgalabru** [comment]
Addressed with https://github.com/hirosystems/clarinet/pull/100
